# Primer Codigo -

Primera Ejecucion

In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd


#Leyendo el archivo CSV
data= pd.read_csv("fetal_health.csv", sep=",", header=[0])
print(data.describe())
X = data.iloc[:, :-1].values
print(X[0])
Y = data.iloc[:,21].values
print(Y)

from sklearn.impute import SimpleImputer
from sklearn import preprocessing

#Preprosesamiento 1, rellenar con la media los espacios faltantes

imputer = SimpleImputer(missing_values=np.NaN, strategy='mean')
imputer = imputer.fit(X)
X= imputer.transform(X)

#Preprosesamiento 2, normalizar los datos

X=preprocessing.normalize(X)
#print(X)

from sklearn.model_selection import StratifiedShuffleSplit
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import confusion_matrix
from sklearn.metrics import precision_score
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
#clasificador=MLPClassifier(hidden_layer_sizes=(128,64,32), solver='adam',max_iter=500)
#clasificador=MLPClassifier()
#clasificador = DecisionTreeClassifier()
clasificador =LogisticRegression(random_state = 0)
clasificador.fit(X,Y)
y_obtenido=clasificador.predict(X)
matriz=confusion_matrix(y_obtenido,Y)

print("==================================================")
print("Matriz de confusión :                             | ")
print("==================================================")
print(matriz)

print("==================================================")
print("Precisión           :                            | ")
print("==================================================")
print(precision_score(y_obtenido,Y,average='micro'))
print("==================================================")

print("==================================================")
print("Splits             :                            | ")
print("==================================================")


       baseline value  accelerations  fetal_movement  uterine_contractions  \
count     2126.000000    2126.000000     2126.000000           2126.000000   
mean       133.303857       0.003178        0.009481              0.004366   
std          9.840844       0.003866        0.046666              0.002946   
min        106.000000       0.000000        0.000000              0.000000   
25%        126.000000       0.000000        0.000000              0.002000   
50%        133.000000       0.002000        0.000000              0.004000   
75%        140.000000       0.006000        0.003000              0.007000   
max        160.000000       0.019000        0.481000              0.015000   

       light_decelerations  severe_decelerations  prolongued_decelerations  \
count          2126.000000           2126.000000               2126.000000   
mean              0.001889              0.000003                  0.000159   
std               0.002960              0.000057               

In [3]:
shufflesplit=StratifiedShuffleSplit(n_splits=100, test_size=0.20, random_state=0)
cv=shufflesplit.split(X,Y)
confiabilidad1=np.zeros(100)
confiabilidad2=np.zeros(100)
for indice, (train_index, test_index) in enumerate( cv):
    print("-----")
    print("Split: ",indice)
    clasificador.fit(X[train_index],Y[train_index])
    y_obtenido = clasificador.predict(X[test_index])
    print(Y[test_index])
    print(y_obtenido)
    print("")
    print("Matriz de Confusión")
    print(confusion_matrix(y_obtenido,Y[test_index]))
    print("Precisión")
    c1=precision_score(y_obtenido, Y[test_index], average='micro')
    print(c1)
    confiabilidad1[indice]=c1
   

-----
Split:  0
[2. 1. 1. 2. 1. 1. 1. 2. 1. 1. 1. 1. 2. 1. 3. 1. 1. 1. 1. 1. 1. 3. 1. 1.
 1. 1. 1. 3. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 1. 1.
 3. 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 3. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 1.
 2. 1. 1. 1. 2. 1. 3. 3. 3. 1. 1. 3. 1. 1. 1. 2. 2. 1. 1. 1. 3. 1. 1. 3.
 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 2. 2. 1. 1. 1. 3. 1. 2. 1. 1. 3. 1.
 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 1. 2. 1. 3. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1.
 1. 2. 3. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 2. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 3. 3. 3. 1. 1. 1. 2. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 3. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 2. 1. 1. 1. 1.
 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 3. 1.
 1. 1. 1. 1. 1. 1. 3. 1. 1. 1. 1. 1. 1. 1. 2. 3. 1. 1. 1. 1. 2. 1. 2. 1.
 1. 1. 2. 3. 1. 1. 1. 1. 1. 3. 1. 3. 1. 2. 1. 1. 2. 2. 3. 1. 1. 2. 2. 1.
 1. 1. 1. 2. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 2. 1. 2. 1. 1. 2. 1. 1. 1. 1.
 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 2. 2

 1. 2. 1. 1. 3. 1. 2. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 1.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 3. 1. 2. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 2. 2. 1. 1. 1. 1. 3. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 2. 2. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 3. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2.
 1. 1. 3. 1. 1. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 2. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 3.
 2. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1

[3. 1. 1. 1. 1. 2. 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 1. 3. 1. 1. 3. 1. 1.
 1. 2. 2. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 2. 1.
 2. 1. 1. 3. 1. 2. 1. 1. 1. 1. 3. 1. 1. 1. 1. 1. 1. 2. 1. 1. 2. 2. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 2. 2. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 2. 1. 1. 1. 2. 1. 1. 1. 1. 2. 1. 1. 3. 2. 1. 1. 1. 3. 1. 3. 1.
 2. 2. 1. 1. 2. 1. 2. 1. 1. 2. 1. 1. 1. 1. 1. 2. 2. 1. 1. 1. 1. 3. 2. 2.
 1. 1. 1. 3. 1. 1. 1. 1. 1. 1. 2. 1. 2. 2. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1.
 3. 1. 1. 1. 1. 1. 1. 1. 1. 1. 3. 3. 2. 3. 3. 3. 1. 2. 1. 1. 1. 3. 1. 1.
 1. 1. 1. 1. 1. 1. 2. 3. 2. 1. 3. 2. 3. 1. 1. 2. 1. 1. 1. 2. 1. 1. 3. 1.
 1. 1. 1. 3. 1. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 3. 1. 3. 3. 1. 1.
 1. 1. 3. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 1. 1. 3. 1.
 1. 1. 2. 2. 1. 1. 3. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 3. 1. 1. 1. 1. 1. 1.
 1. 1. 2. 2. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.

 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 1.]

Matriz de Confusión
[[330  52  22]
 [  2   7   5]
 [  0   0   8]]
Precisión
0.8098591549295775
-----
Split:  12
[1. 1. 1. 1. 3. 1. 1. 1. 2. 2. 2. 2. 3. 2. 1. 1. 1. 1. 1. 1. 1. 1. 2. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 2. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 3. 1. 2. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 3. 1. 1. 1. 1. 3. 2. 1. 1. 1. 1. 1. 1. 1. 1. 1. 3. 1. 1. 2.
 3. 2. 2. 3. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 1. 1. 3. 1. 1. 1. 1. 2. 1. 2.
 1. 3. 1. 1. 1. 2. 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 2. 2. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 2. 1. 3. 1. 2. 1. 1. 1. 2. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 3. 1. 1. 3. 1. 1. 3. 1. 2. 1. 1. 3. 1. 3. 1. 3. 2.
 1. 1. 1. 3. 2. 1. 2. 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 3. 1. 1. 1. 3. 3. 1.
 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 2. 3.
 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 2.
 2. 2. 1. 2. 1. 1. 1. 1. 1. 

Split:  15
[1. 1. 1. 2. 1. 1. 1. 2. 1. 1. 1. 2. 1. 1. 3. 1. 1. 1. 1. 2. 1. 1. 1. 1.
 1. 1. 1. 2. 1. 2. 1. 1. 1. 2. 1. 1. 2. 1. 3. 1. 3. 1. 1. 1. 2. 1. 1. 1.
 1. 1. 2. 1. 2. 1. 1. 1. 1. 1. 3. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 1.
 1. 3. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 3. 3. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2.
 1. 3. 2. 2. 1. 2. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 3. 1. 2. 1. 2. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 1. 2. 1. 1. 1. 1. 2. 1. 2. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 3. 1. 1. 1. 1. 3. 1. 1. 1. 2. 1. 1. 2. 1. 1. 1. 3. 1.
 1. 2. 1. 1. 1. 3. 3. 1. 1. 3. 1. 1. 1. 1. 1. 2. 2. 1. 1. 2. 1. 1. 1. 1.
 1. 1. 3. 1. 3. 1. 2. 1. 1. 3. 1. 1. 1. 1. 1. 1. 1. 3. 1. 1. 1. 1. 1. 2.
 1. 3. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 2. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 1. 3. 1. 1. 1. 1. 1. 1. 2. 1. 1. 2. 1. 1.
 1. 2. 3. 1. 1. 1. 1. 2. 1. 3. 1. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 2.
 1. 1. 1. 2. 1. 1. 1. 2. 1. 1. 1. 3. 1. 1. 1. 1. 1. 1. 1. 1. 1. 3. 1. 2.
 1. 1. 1. 1. 1. 1. 1. 2. 1. 2. 1. 1. 1. 

 1. 1. 1. 1. 2. 1. 1. 2. 1. 1. 2. 1. 2. 1. 1. 2. 3. 1.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 3. 1. 1. 1. 2. 1. 1. 1. 1. 3. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 3. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 3. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 3. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 1.
 1. 2. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 2. 2. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 3. 2. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 3. 1. 2. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 2. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 3. 1. 1. 1. 1. 1. 1

[1. 1. 1. 2. 3. 1. 1. 1. 1. 1. 3. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 1. 1.
 1. 1. 1. 1. 1. 2. 1. 2. 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 3. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 2. 2. 1. 1. 1. 1. 2. 1.
 1. 1. 3. 1. 1. 1. 1. 1. 1. 1. 1. 3. 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 2. 2. 1. 1. 1. 1. 1. 1. 1. 1. 3. 1. 1. 1. 1. 1. 1. 1. 3. 3.
 1. 1. 1. 1. 1. 2. 3. 1. 1. 1. 2. 1. 1. 1. 2. 2. 1. 1. 1. 1. 1. 1. 1. 1.
 2. 2. 2. 2. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1.
 1. 2. 1. 1. 2. 2. 1. 1. 2. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 3.
 1. 2. 3. 1. 1. 1. 1. 1. 2. 2. 2. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 2. 1. 1. 1. 1. 1. 3. 1. 1. 1. 2. 1. 1. 3. 1. 1. 1. 1. 3. 1. 1. 1. 1. 2.
 1. 3. 1. 3. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 3. 2. 1. 1. 3. 1.
 1. 3. 1. 1. 1. 1. 1. 1. 1. 1. 1. 3. 1. 1. 1. 1. 1. 1. 1. 3. 3. 1. 1. 1.
 1. 2. 2. 1. 1. 1. 2. 2. 1. 3. 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 2. 1. 1. 1. 1. 1. 2. 1. 1. 1. 2. 1. 1. 1. 1. 1.

0.8028169014084507
-----
Split:  27
[1. 1. 3. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2.
 1. 2. 1. 2. 1. 1. 1. 1. 1. 1. 2. 2. 1. 2. 1. 1. 1. 1. 1. 1. 1. 2. 1. 1.
 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 3. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 3. 1.
 1. 1. 2. 1. 1. 2. 1. 2. 1. 1. 1. 1. 1. 1. 3. 1. 2. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 1. 2.
 1. 1. 1. 1. 2. 1. 1. 1. 2. 1. 1. 1. 1. 1. 2. 1. 3. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 2. 1. 1. 3. 1. 1. 1. 3. 1. 3. 1. 2. 1. 1. 1. 1. 1. 1. 1.
 1. 3. 1. 1. 2. 3. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 3. 1. 1. 1. 1. 1. 2. 2.
 1. 2. 1. 1. 1. 1. 1. 2. 3. 1. 1. 3. 1. 2. 1. 1. 1. 1. 3. 1. 2. 3. 1. 1.
 1. 1. 1. 1. 3. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 3.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 1. 3. 3. 1. 1. 1. 1. 2. 1. 3. 1. 1.
 2. 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 2. 1. 1. 3. 2. 1. 1.
 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 2. 1. 3. 2. 1. 3. 1. 1. 1. 1.
 3. 2. 2. 1. 1.

0.812206572769953
-----
Split:  31
[1. 1. 1. 1. 1. 1. 1. 1. 3. 1. 1. 1. 1. 1. 2. 2. 1. 1. 1. 1. 1. 1. 2. 3.
 1. 1. 2. 1. 3. 1. 1. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 1. 2. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 2. 1. 1. 2. 1. 1. 2. 1. 1. 1. 1. 1. 3. 1. 1. 1. 1. 1. 3. 1.
 1. 1. 1. 1. 1. 3. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 1. 3. 2. 1. 1. 1. 1.
 2. 1. 1. 3. 1. 2. 1. 1. 1. 2. 1. 1. 1. 1. 1. 3. 1. 3. 2. 1. 1. 1. 3. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 3. 1. 1. 1. 2. 1. 2. 1. 2. 2. 1. 1. 1. 1. 2. 1. 1. 2. 1. 1.
 1. 1. 1. 1. 1. 3. 1. 1. 1. 2. 1. 1. 1. 3. 1. 2. 1. 1. 3. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 3. 1. 3. 1. 2. 1. 1. 1. 3. 1. 2.
 2. 1. 1. 1. 1. 3. 1. 1. 2. 2. 1. 3. 1. 1. 2. 1. 2. 2. 1. 1. 1. 2. 1. 1.
 1. 3. 1. 1. 1. 1. 3. 1. 1. 2. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 2. 1. 1. 1.
 1. 1. 1. 1. 1. 3. 2. 1. 1. 3. 1. 1. 1. 2. 1. 3. 1. 1. 1. 1. 1. 1. 2. 1.
 1. 1. 1. 1. 1. 

0.8075117370892019
-----
Split:  35
[1. 1. 2. 1. 1. 1. 1. 1. 3. 1. 1. 1. 3. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 3. 1. 2. 1. 2. 1. 1. 2. 1. 1. 1. 1. 3. 1. 1. 1. 1. 1. 2. 1. 3. 1.
 1. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 2. 1. 1. 1. 3. 1. 1. 1. 2. 1. 1.
 1. 3. 1. 1. 1. 2. 1. 1. 1. 1. 2. 1. 2. 1. 1. 1. 1. 2. 1. 1. 1. 1. 3. 1.
 1. 1. 1. 1. 1. 1. 1. 3. 3. 1. 1. 2. 1. 1. 1. 3. 1. 1. 2. 1. 1. 2. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 3. 1. 3. 1. 1. 2. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 3. 1. 1. 1. 1. 1. 2. 1. 1. 1. 2. 1.
 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 1. 1. 3. 1. 1. 2. 2. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 3. 2. 1. 2. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 2. 1. 1. 1.
 2. 1. 1. 1. 1. 1. 1. 1. 2. 2. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1.
 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 2. 3. 1. 1. 1. 3. 3. 2.
 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 2. 1. 1. 2. 1. 1. 2. 1. 3. 1. 1. 1. 1. 1.
 1. 3. 1. 1. 2. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 3. 1. 1. 2. 1. 1. 1. 3. 1.
 1. 1. 1. 1. 1.

 1. 3. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 2. 2. 1. 1.]

Matriz de Confusión
[[326  51  20]
 [  6   7   8]
 [  0   1   7]]
Precisión
0.7981220657276995
-----
Split:  39
[2. 1. 1. 1. 1. 1. 1. 1. 1. 3. 1. 3. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 3. 1.
 2. 1. 1. 1. 1. 3. 1. 1. 1. 1. 3. 1. 1. 1. 2. 1. 1. 1. 1. 3. 2. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 3. 1. 1. 2. 1. 1. 1. 1. 1. 2.
 3. 1. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2.
 1. 1. 1. 1. 1. 1. 1. 2. 3. 1. 1. 1. 1. 1. 1. 1. 3. 1. 1. 1. 1. 2. 1. 1.
 1. 1. 1. 3. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 1. 3. 1. 2. 1. 1. 1. 1. 1. 1.
 2. 1. 1. 1. 1. 1. 1. 3. 1. 2. 1. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 3.
 3. 1. 1. 1. 2. 1. 3. 1. 2. 1. 1. 1. 1. 1. 1. 1. 1. 1. 3. 1. 1. 1. 1. 1.
 1. 2. 1. 1. 1. 1. 2. 2. 1. 3. 1. 1. 1. 2. 1. 1. 1. 1. 2. 2. 2. 1. 2. 1.
 1. 1. 3. 1. 1. 2. 1. 3. 1. 1. 3. 1. 1. 1. 1. 1. 3. 3. 1. 1. 1. 1. 3. 1.
 2. 1. 2. 3. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 2. 1. 2. 2. 1.
 2. 1. 1. 1. 2. 2. 1. 1. 1. 

 1. 2. 1. 1. 3. 2. 2. 1. 1. 1. 1. 1. 1. 2. 1. 3. 1. 2.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 3. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 1. 2. 1.
 1. 2. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 3. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 3. 1. 1. 3. 1. 2. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 3. 1. 1. 1. 1.
 1. 3. 1. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 2. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1

 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1.]

Matriz de Confusión
[[328  51  18]
 [  4   8   8]
 [  0   0   9]]
Precisión
0.8098591549295775
-----
Split:  47
[1. 2. 1. 2. 3. 1. 1. 1. 1. 1. 1. 1. 2. 1. 3. 2. 1. 1. 2. 2. 1. 1. 1. 1.
 1. 3. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 2. 2. 3. 1. 2. 2. 1. 1. 1.
 2. 1. 1. 1. 1. 3. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 2. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 3. 1. 2. 2.
 1. 1. 1. 1. 3. 1. 1. 3. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 3. 1. 1. 1. 1. 1.
 1. 2. 1. 2. 1. 1. 1. 1. 1. 3. 1. 1. 2. 1. 1. 1. 1. 1. 1. 3. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 2. 1. 2. 1. 3. 1. 1. 1. 1. 1. 1. 2. 1. 1. 3. 3. 1. 1.
 1. 1. 1. 1. 1. 1. 2. 2. 1. 2. 1. 1. 1. 1. 1. 1. 3. 3. 1. 1. 3. 1. 1. 1.
 1. 1. 1. 2. 2. 3. 1. 1. 1. 1. 1. 1. 1. 1. 2. 1. 1. 2. 2. 1. 1. 3. 1. 1.
 1. 1. 1. 1. 3. 1. 1. 2. 1. 1. 1. 2. 1. 1. 3. 1. 1. 2. 1. 2. 1. 2. 2. 3.
 2. 1. 2. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1.
 1. 3. 1. 1. 2. 1. 1. 1. 1. 

 [  0   0   7]]
Precisión
0.8051643192488263
-----
Split:  50
[1. 1. 1. 1. 1. 1. 3. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 1. 1. 3. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2.
 1. 1. 1. 3. 1. 1. 1. 1. 1. 3. 2. 1. 1. 2. 1. 1. 1. 1. 1. 2. 3. 2. 1. 2.
 1. 1. 1. 2. 3. 1. 1. 1. 1. 2. 1. 1. 1. 2. 2. 3. 1. 1. 1. 1. 1. 2. 1. 1.
 1. 1. 1. 2. 1. 1. 1. 3. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 2. 1. 1. 1. 1. 2. 1. 1. 2. 1. 3. 2. 1. 1. 1. 1. 3. 1. 1. 2. 3. 1. 2. 1.
 2. 1. 2. 2. 1. 1. 1. 1. 1. 1. 2. 1. 3. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 3. 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 1. 1. 3. 1. 1.
 2. 2. 1. 1. 3. 2. 1. 1. 2. 1. 1. 1. 1. 2. 1. 3. 1. 1. 3. 2. 1. 1. 1. 1.
 2. 1. 3. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 3. 2. 1. 1. 1. 2. 1.
 1. 1. 1. 3. 1. 1. 1. 1. 2. 1. 1. 1. 3. 1. 1. 1. 1. 1. 1. 1. 1. 2. 3. 1.
 1. 2. 2. 3. 1. 1. 1. 1. 1. 2. 1. 1. 3. 1. 1. 1. 3. 1. 1. 1. 1. 3. 1. 1.
 1. 1. 3. 3. 2. 1. 1. 1. 1. 1. 1. 1. 2. 2. 1. 1. 1. 1. 1. 1. 1

 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]

Matriz de Confusión
[[331  50  17]
 [  1   9   6]
 [  0   0  12]]
Precisión
0.8262910798122066
-----
Split:  55
[1. 2. 1. 1. 1. 1. 1. 2. 2. 2. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 3. 1. 1. 1.
 1. 1. 1. 1. 1. 2. 1. 3. 2. 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 2. 1. 1.
 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 1. 2. 1. 2. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1.
 1. 3. 1. 1. 1. 2. 1. 1. 3. 1. 1. 1. 1. 2. 1. 1. 1. 2. 1. 1. 3. 2. 1. 3.
 1. 1. 1. 1. 1. 2. 3. 1. 1. 1. 3. 1. 1. 3. 2. 1. 1. 1. 2. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 3. 1. 1. 1. 1. 1. 1.
 1. 2. 1. 1. 1. 3. 3. 1. 1. 3. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 3. 1. 1. 1.
 3. 1. 1. 2. 1. 1. 1. 1. 2. 1. 1. 3. 1. 1. 1. 2. 1. 1. 1. 3. 1. 1. 2. 1.
 1. 3. 1. 1. 1. 1. 1. 1. 1. 1. 2. 1. 3. 3. 1. 2. 1. 1. 1. 1. 1. 2. 1. 1.
 1. 3. 1. 3. 2. 1. 1. 3. 1. 1. 1. 1. 1. 1. 1. 2. 3. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 2. 1. 1. 2. 1. 3. 1. 1. 1. 1. 3. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 2. 1. 

0.7910798122065728
-----
Split:  59
[3. 1. 2. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 2. 1. 2. 1. 1. 1. 1.
 1. 1. 1. 3. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 1. 2. 3. 1. 1. 1.
 2. 1. 1. 1. 1. 1. 1. 1. 2. 1. 2. 1. 3. 1. 1. 1. 1. 3. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 3. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 1. 1. 2.
 1. 1. 1. 1. 1. 1. 1. 3. 1. 2. 3. 1. 1. 2. 2. 1. 2. 1. 1. 2. 3. 1. 1. 1.
 1. 2. 1. 1. 1. 3. 2. 1. 1. 1. 1. 1. 1. 3. 3. 2. 1. 1. 1. 1. 1. 3. 1. 1.
 1. 1. 1. 1. 2. 1. 1. 1. 1. 3. 3. 1. 1. 1. 1. 2. 1. 1. 3. 1. 1. 1. 1. 2.
 1. 1. 1. 1. 1. 1. 3. 1. 1. 2. 1. 3. 1. 2. 1. 1. 2. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 2. 2. 1. 2. 1. 2. 1. 1. 1. 1. 1. 1. 1. 1. 2. 1. 2. 1. 1. 1. 1. 1.
 2. 3. 3. 1. 1. 1. 2. 1. 1. 1. 2. 2. 1. 1. 3. 1. 2. 3. 1. 2. 2. 1. 1. 1.
 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 3.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 1. 1. 2. 2. 1. 1. 3. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 2.

-----
Split:  63
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 3. 1. 3. 3. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 2. 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 3.
 3. 1. 3. 2. 1. 1. 1. 1. 1. 1. 3. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 2. 2. 3. 3. 2. 1. 3. 1. 1. 1. 3. 1. 3. 1. 1. 1. 1. 3. 1. 1. 1. 1. 1. 2.
 1. 1. 1. 1. 2. 1. 3. 1. 3. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2.
 3. 1. 1. 3. 1. 1. 1. 1. 1. 1. 1. 3. 3. 1. 1. 1. 1. 1. 1. 1. 1. 3. 1. 2.
 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 1. 2. 2. 2. 1. 1. 2. 1. 1. 1. 1. 1. 1. 1.
 1. 2. 1. 3. 2. 1. 1. 1. 2. 1. 3. 1. 1. 1. 1. 3. 1. 1. 1. 1. 2. 1. 2. 1.
 1. 1. 1. 1. 1. 1. 2. 1. 1. 3. 1. 1. 1. 3. 1. 1. 1. 2. 1. 1. 1. 1. 1. 2.
 1. 1. 1. 1. 1. 2. 1. 3. 1. 2. 1. 1. 1. 1. 1. 3. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 2. 1. 2. 1. 1. 2.
 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 3. 1. 1. 2. 1. 2. 1. 1. 1. 1. 3.
 1. 1. 1. 1. 1. 2. 2. 1. 1. 1. 1. 

[1. 1. 1. 1. 1. 1. 1. 3. 2. 1. 1. 1. 1. 1. 1. 3. 1. 1. 1. 1. 1. 2. 1. 1.
 1. 1. 1. 1. 2. 1. 3. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 3. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 3. 1. 1. 1. 1. 2. 1. 1.
 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 2. 1. 1. 1. 3. 1. 1. 2. 1. 1. 1. 2.
 1. 1. 2. 1. 1. 1. 1. 1. 3. 2. 2. 1. 1. 1. 2. 1. 1. 3. 3. 1. 1. 1. 1. 3.
 2. 1. 1. 1. 2. 1. 2. 1. 1. 1. 1. 3. 3. 2. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 3. 1. 1. 1. 2. 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 1. 2. 2. 1. 3. 1. 1.
 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 3. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 3. 1. 1. 1. 1. 2. 1. 2.
 2. 1. 1. 1. 1. 3. 1. 1. 1. 1. 1. 1. 3. 1. 1. 1. 2. 1. 1. 2. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 3. 1. 1. 1. 1. 2. 1. 1. 2. 2. 1. 1. 3. 1. 1. 1. 1.
 2. 1. 1. 2. 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 3. 1. 1. 1. 1. 1. 2. 1.
 2. 1. 1. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 3. 1. 1.
 2. 1. 1. 2. 2. 1. 3. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.

 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2.]

Matriz de Confusión
[[330  48  19]
 [  2  10   9]
 [  0   1   7]]
Precisión
0.8145539906103286
-----
Split:  71
[1. 1. 1. 1. 3. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 3. 3. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 3. 1. 1. 3. 1. 1. 2. 1. 1. 1. 1. 3. 1. 2. 1. 1. 1. 1. 1. 1. 2.
 1. 1. 1. 1. 1. 1. 1. 3. 1. 1. 1. 3. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 3. 2.
 1. 2. 1. 1. 1. 1. 1. 1. 1. 2. 1. 2. 2. 1. 3. 1. 1. 1. 3. 1. 1. 1. 1. 1.
 1. 1. 1. 3. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 1. 2. 1. 1. 2. 1. 1. 1. 1.
 1. 1. 1. 1. 3. 1. 1. 1. 1. 2. 1. 2. 2. 1. 1. 1. 2. 1. 1. 2. 1. 1. 1. 3.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 2. 1. 1. 1. 2. 2. 2. 1.
 1. 3. 1. 1. 3. 1. 2. 1. 1. 1. 1. 1. 1. 1. 3. 1. 1. 2. 1. 1. 2. 3. 2. 1.
 2. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 3. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 3. 1. 1. 1. 1. 3. 1.
 1. 1. 1. 1. 1. 1. 1. 3. 3. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 

Split:  75
[1. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 3. 1. 1. 1. 1. 1. 1. 1. 2. 1.
 1. 1. 1. 1. 2. 1. 1. 2. 1. 1. 1. 1. 3. 1. 1. 1. 2. 1. 1. 3. 1. 1. 2. 1.
 1. 2. 1. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1.
 1. 2. 3. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 3. 3. 1. 1. 1. 2. 1. 1. 1. 1. 2. 3. 3. 2. 1. 1. 2. 2. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 3. 2. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 2. 3. 1. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1.
 1. 2. 1. 1. 1. 1. 1. 1. 1. 3. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 2. 1. 2. 2. 1. 3. 3. 1. 1. 1. 1. 1. 2. 1. 3. 1. 1. 2. 2. 1.
 2. 2. 3. 2. 1. 1. 3. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 3. 1. 2. 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 3.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 3. 3. 1. 1. 1. 1. 1. 3. 1. 1. 3. 1. 3.
 3. 1. 1. 1. 3. 1. 2. 1. 3. 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 1. 1. 3. 1. 1.
 1. 2. 1. 1. 1. 1. 3. 2. 1. 1. 1. 1. 2. 

 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 1. 1. 2. 1. 2. 1. 1. 1.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 3. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 2. 1. 2. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 3. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 2. 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 1. 1.
 1. 1. 1. 1. 1. 2. 1. 2. 1. 1. 2. 1. 1. 1. 2. 1. 1. 1. 2. 1. 1. 2. 2. 1.
 1. 1. 1. 1. 3. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 3. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 2. 3.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 3. 1. 1. 1. 1. 1. 1. 1. 1. 1

 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 1.]
[1. 1. 1. 1. 1. 3. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 2. 1. 2. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 2.
 1. 2. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 1. 3. 1. 3. 1. 1. 2. 1. 2. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 2. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 3. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1

[1. 1. 1. 1. 1. 1. 1. 3. 2. 3. 1. 1. 1. 3. 1. 1. 1. 1. 1. 3. 2. 1. 1. 2.
 1. 1. 1. 1. 2. 1. 1. 3. 1. 1. 1. 2. 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 3. 2. 1. 3. 1. 2. 1. 1. 1. 1. 1. 2. 1. 1. 2.
 1. 2. 1. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 1. 2. 1. 1. 2. 1. 1.
 1. 3. 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 3. 1.
 1. 1. 2. 2. 1. 1. 1. 1. 1. 3. 1. 1. 2. 1. 1. 1. 1. 2. 1. 1. 3. 1. 1. 2.
 2. 1. 1. 2. 1. 2. 1. 1. 1. 2. 3. 1. 3. 1. 2. 1. 1. 1. 2. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 2. 1. 1. 1. 3. 1. 1. 1. 1. 3. 1. 3. 3. 1.
 1. 1. 1. 1. 1. 3. 1. 3. 1. 1. 1. 1. 2. 1. 3. 2. 2. 1. 1. 1. 1. 2. 2. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 1. 1. 2. 1. 1. 1. 1. 1. 2. 1. 1.
 1. 1. 3. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 3. 1. 1.
 2. 1. 2. 1. 2. 1. 2. 1. 2. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 2. 3. 2. 2. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 1. 1. 3. 1. 2. 1. 1. 1. 1.
 2. 1. 3. 1. 3. 1. 1. 1. 2. 1. 1. 1. 1. 1. 3. 1. 1.

 2. 1. 1. 1. 1. 1. 1. 3. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 1. 1. 3. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 3. 1. 1. 2.
 1. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 3. 1. 1.
 1. 1. 2. 1. 1. 1. 1. 1. 2. 1. 2. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 1. 1. 3. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 3. 1. 1. 1. 1. 3. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 3. 1. 1. 1. 1. 1. 3. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 3. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1

 1. 1. 2. 1. 1. 1. 2. 1. 1. 3. 3. 1. 1. 3. 1. 1. 1. 2.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 2. 1. 1. 1. 1. 1.
 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 3. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 3. 1. 1. 1. 1. 1. 3. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 1. 1. 2. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 3. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 3. 2. 1. 2. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 2. 1. 1. 1. 1. 1. 1. 1. 3. 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2

 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]

Matriz de Confusión
[[329  53  15]
 [  3   6   9]
 [  0   0  11]]
Precisión
0.812206572769953
-----
Split:  99
[1. 2. 1. 2. 3. 2. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 3. 1. 1. 1.
 1. 1. 1. 1. 1. 2. 3. 1. 1. 1. 3. 1. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 3. 3. 1. 1. 1. 1. 2. 1. 1. 1. 1. 2. 1. 1. 2. 1. 1. 1. 1. 1. 2. 1.
 1. 2. 1. 1. 1. 1. 2. 2. 3. 1. 1. 1. 1. 1. 1. 2. 2. 1. 1. 1. 1. 2. 1. 1.
 1. 1. 1. 1. 1. 2. 1. 2. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 3. 1. 1. 3. 1. 1. 2. 1. 1. 1. 1. 1. 3. 1. 1. 3. 1. 2.
 1. 1. 1. 1. 1. 2. 1. 3. 1. 1. 1. 1. 1. 1. 3. 1. 2. 1. 1. 1. 2. 3. 1. 2.
 3. 2. 2. 1. 2. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 2. 1. 1. 1. 2. 1. 1.
 1. 1. 2. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 3. 1. 1. 2. 1. 1. 1. 2.
 1. 1. 3. 3. 1. 1. 2. 1. 2. 2. 2. 2. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2.
 1. 1. 1. 2. 1. 2. 1. 1. 1. 1

In [7]:
    print("==================================================")
    print("Confiabidad 80(train)/20(test)    :             | ")
    print("==================================================")
    print(np.median(confiabilidad1))
    print("==================================================")

Confiabidad 80(train)/20(test)    :             | 
0.8075117370892019


In [8]:
shufflesplit=StratifiedShuffleSplit(n_splits=100, test_size=0.50, random_state=0)
cv=shufflesplit.split(X,Y)
confiabilidad=np.zeros(100)
for indice, (train_index, test_index) in enumerate( cv):
    print("-----")
    print("Split: ",indice)
    clasificador.fit(X[train_index],Y[train_index])
    y_obtenido = clasificador.predict(X[test_index])
    print(Y[test_index])
    print(y_obtenido)
    print("")
    print("Matriz de Confusión")
    print(confusion_matrix(y_obtenido,Y[test_index]))
    print("Precisión")
    c1=precision_score(y_obtenido, Y[test_index], average='micro')
    print(c1)
    confiabilidad2[indice]=c1
    

-----
Split:  0
[1. 1. 1. ... 1. 1. 1.]
[1. 1. 1. ... 1. 1. 1.]

Matriz de Confusión
[[823 140  58]
 [  5   6  17]
 [  0   1  13]]
Precisión
0.7920978363123237
-----
Split:  1
[1. 1. 1. ... 1. 1. 1.]
[1. 1. 1. ... 1. 1. 1.]

Matriz de Confusión
[[823 141  59]
 [  5   6  17]
 [  0   0  12]]
Precisión
0.7911571025399812
-----
Split:  2
[1. 1. 1. ... 1. 1. 1.]
[1. 1. 1. ... 1. 1. 1.]

Matriz de Confusión
[[823 143  58]
 [  4   5  19]
 [  0   0  11]]
Precisión
0.7892756349952963
-----
Split:  3
[1. 1. 1. ... 1. 1. 1.]
[1. 1. 1. ... 1. 1. 1.]

Matriz de Confusión
[[820 136  50]
 [  7  12  23]
 [  0   0  15]]
Precisión
0.7968015051740357
-----
Split:  4
[2. 1. 1. ... 1. 1. 1.]
[1. 1. 1. ... 1. 1. 1.]

Matriz de Confusión
[[823 140  53]
 [  5   7  20]
 [  0   0  15]]
Precisión
0.7949200376293509
-----
Split:  5
[2. 1. 2. ... 1. 1. 1.]
[1. 1. 2. ... 1. 1. 1.]

Matriz de Confusión
[[819 141  59]
 [  9   6  14]
 [  0   0  15]]
Precisión
0.7902163687676388
-----
Split:  6
[1. 1. 1. ... 1. 1. 1.]


-----
Split:  52
[3. 1. 1. ... 1. 1. 1.]
[1. 1. 1. ... 1. 1. 1.]

Matriz de Confusión
[[816 135  58]
 [ 12  12  20]
 [  0   0  10]]
Precisión
0.7883349012229539
-----
Split:  53
[1. 1. 1. ... 2. 1. 1.]
[1. 1. 1. ... 1. 1. 1.]

Matriz de Confusión
[[822 143  57]
 [  5   5  18]
 [  0   0  13]]
Precisión
0.7902163687676388
-----
Split:  54
[3. 1. 1. ... 1. 1. 1.]
[1. 1. 1. ... 1. 1. 1.]

Matriz de Confusión
[[819 136  47]
 [  9  11  23]
 [  0   0  18]]
Precisión
0.7977422389463782
-----
Split:  55
[2. 1. 2. ... 3. 2. 2.]
[1. 1. 1. ... 1. 1. 1.]

Matriz de Confusión
[[824 140  57]
 [  4   7  16]
 [  0   0  15]]
Precisión
0.7958607714016933
-----
Split:  56
[1. 1. 1. ... 1. 1. 1.]
[1. 1. 1. ... 1. 1. 1.]

Matriz de Confusión
[[821 139  57]
 [  6   9  18]
 [  0   0  13]]
Precisión
0.793038570084666
-----
Split:  57
[1. 1. 1. ... 1. 1. 1.]
[1. 1. 1. ... 1. 1. 1.]

Matriz de Confusión
[[820 137  56]
 [  8   9  20]
 [  0   1  12]]
Precisión
0.7911571025399812
-----
Split:  58
[1. 2. 1. ... 1. 2

In [ ]:

print("==================================================")
print("Confiabidad 50(train)/50(test)    :             | ")
print("==================================================")
print(np.median(confiabilidad2))
print("==================================================")