# Primer Codigo -

Primera Ejecucion

In [5]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd


#Leyendo el archivo CSV
data= pd.read_csv("fetal_health.csv", sep=",", header=[0])
print(data.describe())
X = data.iloc[:, :-1].values
print(X[0])
Y = data.iloc[:,21].values
print(Y)

from sklearn.impute import SimpleImputer
from sklearn import preprocessing

#Preprosesamiento 1, rellenar con la media los espacios faltantes

imputer = SimpleImputer(missing_values=np.NaN, strategy='mean')
imputer = imputer.fit(X)
X= imputer.transform(X)

#Preprosesamiento 2, normalizar los datos

X=preprocessing.normalize(X)
#print(X)

from sklearn.model_selection import StratifiedShuffleSplit
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import confusion_matrix
from sklearn.metrics import precision_score
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
#clasificador=MLPClassifier(hidden_layer_sizes=(128,64,32), solver='adam',max_iter=500)
#clasificador=MLPClassifier()
clasificador = DecisionTreeClassifier()
#clasificador =LogisticRegression(random_state = 0)
clasificador.fit(X,Y)
y_obtenido=clasificador.predict(X)
matriz=confusion_matrix(y_obtenido,Y)

print("==================================================")
print("Matriz de confusión :                             | ")
print("==================================================")
print(matriz)

print("==================================================")
print("Precisión           :                            | ")
print("==================================================")
print(precision_score(y_obtenido,Y,average='micro'))
print("==================================================")

print("==================================================")
print("Splits             :                            | ")
print("==================================================")


       baseline value  accelerations  fetal_movement  uterine_contractions  \
count     2126.000000    2126.000000     2126.000000           2126.000000   
mean       133.303857       0.003178        0.009481              0.004366   
std          9.840844       0.003866        0.046666              0.002946   
min        106.000000       0.000000        0.000000              0.000000   
25%        126.000000       0.000000        0.000000              0.002000   
50%        133.000000       0.002000        0.000000              0.004000   
75%        140.000000       0.006000        0.003000              0.007000   
max        160.000000       0.019000        0.481000              0.015000   

       light_decelerations  severe_decelerations  prolongued_decelerations  \
count          2126.000000           2126.000000               2126.000000   
mean              0.001889              0.000003                  0.000159   
std               0.002960              0.000057               

In [2]:
shufflesplit=StratifiedShuffleSplit(n_splits=100, test_size=0.20, random_state=0)
cv=shufflesplit.split(X,Y)
confiabilidad1=np.zeros(100)
confiabilidad2=np.zeros(100)
for indice, (train_index, test_index) in enumerate( cv):
    print("-----")
    print("Split: ",indice)
    clasificador.fit(X[train_index],Y[train_index])
    y_obtenido = clasificador.predict(X[test_index])
    print(Y[test_index])
    print(y_obtenido)
    print("")
    print("Matriz de Confusión")
    print(confusion_matrix(y_obtenido,Y[test_index]))
    print("Precisión")
    c1=precision_score(y_obtenido, Y[test_index], average='micro')
    print(c1)
    confiabilidad1[indice]=c1
   

-----
Split:  0
[2. 1. 1. 2. 1. 1. 1. 2. 1. 1. 1. 1. 2. 1. 3. 1. 1. 1. 1. 1. 1. 3. 1. 1.
 1. 1. 1. 3. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 1. 1.
 3. 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 3. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 1.
 2. 1. 1. 1. 2. 1. 3. 3. 3. 1. 1. 3. 1. 1. 1. 2. 2. 1. 1. 1. 3. 1. 1. 3.
 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 2. 2. 1. 1. 1. 3. 1. 2. 1. 1. 3. 1.
 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 1. 2. 1. 3. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1.
 1. 2. 3. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 2. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 3. 3. 3. 1. 1. 1. 2. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 3. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 2. 1. 1. 1. 1.
 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 3. 1.
 1. 1. 1. 1. 1. 1. 3. 1. 1. 1. 1. 1. 1. 1. 2. 3. 1. 1. 1. 1. 2. 1. 2. 1.
 1. 1. 2. 3. 1. 1. 1. 1. 1. 3. 1. 3. 1. 2. 1. 1. 2. 2. 3. 1. 1. 2. 2. 1.
 1. 1. 1. 2. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 2. 1. 2. 1. 1. 2. 1. 1. 1. 1.
 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 2. 2

[1. 1. 1. 1. 1. 1. 3. 1. 1. 3. 2. 1. 1. 2. 1. 2. 1. 1. 1. 1. 3. 1. 3. 1.
 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 2. 1. 2. 2. 1. 1. 1. 1. 1. 3. 1. 1.
 1. 1. 1. 2. 1. 1. 1. 2. 1. 3. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2.
 1. 1. 1. 1. 1. 1. 3. 1. 1. 1. 2. 1. 1. 1. 1. 3. 1. 1. 1. 3. 1. 1. 1. 3.
 1. 1. 1. 1. 1. 1. 1. 2. 1. 2. 1. 1. 3. 1. 1. 1. 3. 2. 2. 1. 3. 1. 1. 1.
 2. 1. 2. 1. 2. 1. 1. 1. 3. 1. 1. 2. 2. 1. 1. 1. 1. 1. 2. 1. 3. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 3. 3. 1. 1. 1.
 1. 1. 3. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 2. 1. 1. 1. 1. 1. 1. 1. 1. 1. 3. 1. 2. 1. 3. 1. 2. 1. 1. 2. 1. 1. 1. 2.
 1. 1. 2. 1. 1. 2. 2. 1. 2. 1. 2. 1. 3. 1. 1. 1. 1. 1. 1. 3. 1. 2. 3. 1.
 1. 1. 1. 2. 1. 3. 1. 1. 1. 1. 1. 2. 1. 3. 1. 3. 1. 1. 2. 1. 1. 3. 3. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 1. 2. 1. 2. 1.
 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 1. 1. 2. 1. 1. 1.

[[314  17   2]
 [ 17  41   6]
 [  1   1  27]]
Precisión
0.8967136150234741
-----
Split:  10
[1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2.
 2. 1. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 2. 2. 1. 1. 1.
 1. 1. 1. 1. 2. 1. 1. 2. 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 2. 2. 1. 2. 1. 1.
 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 3. 1. 1.
 1. 2. 1. 1. 1. 1. 1. 2. 1. 2. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 3.
 1. 1. 2. 1. 1. 1. 1. 2. 1. 2. 1. 1. 3. 2. 3. 2. 1. 3. 3. 1. 1. 3. 1. 1.
 3. 3. 3. 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 1. 3. 1.
 1. 1. 3. 1. 1. 1. 1. 2. 1. 2. 2. 2. 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 2. 1. 2. 1. 3. 1. 1. 2. 1. 1. 1. 1. 1. 1. 2. 1. 1. 3. 1. 1. 2. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 3. 3. 1. 1. 1. 3. 1. 2. 1. 1. 1.
 3. 1. 1. 1. 3. 1. 3. 1. 2. 1. 2. 1. 1. 1. 1. 1. 1. 1. 1. 1. 3. 1. 1. 2.
 1. 1. 1. 1. 1. 3. 1. 1. 1. 1. 1

[1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 2. 1. 1.
 2. 1. 2. 2. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 2. 1. 2. 1. 1. 1. 1. 1.
 1. 2. 1. 1. 1. 1. 1. 2. 1. 3. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 1.
 3. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 2. 1. 2. 2. 1. 1. 1.
 3. 1. 2. 3. 1. 1. 2. 1. 1. 1. 2. 1. 2. 3. 2. 1. 1. 1. 1. 3. 1. 1. 3. 3.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 1. 1. 3. 1. 1. 1. 1. 1.
 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 3. 1. 3. 3. 1. 1. 1. 1. 1. 1. 1.
 1. 3. 1. 1. 1. 1. 3. 1. 1. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 2. 1. 3. 1. 1.
 2. 1. 3. 1. 1. 2. 1. 2. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 1. 1.
 1. 3. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 2. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 1.
 2. 1. 1. 1. 2. 1. 3. 1. 1. 1. 1. 1. 2. 1. 1. 2. 1. 1. 1. 1. 3. 1. 1. 1.
 2. 1. 1. 1. 1. 1. 1. 1. 3. 1. 2. 3. 2. 1. 1. 1. 1. 1. 2. 2. 1. 3. 1. 1.
 2. 1. 2. 2. 1. 1. 1. 2. 1. 1. 1. 1. 3. 1. 3. 1. 1.

[2. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 3. 1. 1. 1. 1. 1. 1. 1. 1. 3. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 3. 1. 1. 1. 2. 1. 1. 1. 1. 3. 1. 2. 1. 1. 1. 2.
 1. 1. 1. 3. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 2. 1. 1. 1. 1. 1. 2.
 1. 1. 1. 1. 1. 1. 3. 1. 2. 2. 1. 1. 1. 1. 3. 2. 1. 1. 3. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 3. 1. 3. 1. 1. 1. 1. 1. 1. 1. 1. 1. 3. 2. 1. 3. 1. 2. 2.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 3. 1. 1. 1. 2. 1. 1. 2. 1. 1. 2. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 3. 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 1. 3. 1. 1. 2.
 1. 1. 1. 1. 2. 1. 1. 2. 2. 2. 3. 1. 1. 2. 2. 1. 1. 1. 1. 1. 2. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 3. 1. 1. 1. 1. 1. 1. 1. 3. 2. 1. 1. 1.
 1. 3. 1. 1. 1. 1. 2. 2. 1. 1. 1. 1. 1. 3. 2. 2. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 2. 1. 1. 3. 2. 1. 1. 1. 1. 1. 2. 1. 2. 1. 1. 1. 3. 1. 2. 1.
 1. 1. 1. 1. 1. 2. 2. 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 1. 2. 2. 1.
 1. 3. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 1. 1. 3. 3. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 3. 2. 1. 3. 1. 1. 1. 1. 2. 1.

0.9107981220657277
-----
Split:  25
[1. 1. 1. 2. 2. 1. 2. 3. 1. 1. 2. 1. 3. 1. 1. 1. 2. 3. 1. 3. 1. 1. 2. 1.
 1. 1. 2. 2. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 2. 1. 1. 1. 1. 2. 1. 3. 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 3. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 3. 2. 3. 1. 2. 1.
 1. 1. 1. 2. 1. 1. 1. 1. 1. 3. 1. 3. 2. 1. 2. 1. 1. 1. 1. 1. 1. 3. 1. 1.
 2. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 2. 2. 1. 2. 2. 1. 1. 1. 1.
 1. 3. 1. 1. 2. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 3. 1. 1.
 1. 2. 1. 1. 1. 1. 2. 1. 1. 1. 1. 3. 1. 1. 1. 3. 2. 1. 1. 1. 1. 2. 1. 2.
 1. 1. 1. 1. 1. 1. 2. 1. 3. 1. 1. 3. 1. 3. 3. 2. 2. 3. 1. 1. 1. 1. 1. 1.
 1. 1. 2. 1. 2. 1. 2. 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 3. 3.
 1. 3. 1. 1. 1. 3. 1. 1. 1. 1. 1. 1. 3. 1. 2. 3. 1. 1. 1. 1. 2. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2.
 1. 1. 2. 2. 2. 1. 1. 1. 1. 3. 2. 1. 1. 1. 1. 1. 1. 1. 3. 1. 1. 1. 1. 2.
 1. 1. 1. 1. 3.

[2. 1. 2. 2. 1. 1. 1. 1. 1. 2. 1. 3. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 3. 1. 1. 3. 1. 2. 1. 1. 1. 1. 1. 3. 1. 3. 1. 2. 1. 1. 2. 3. 1. 1.
 3. 1. 3. 3. 3. 3. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 3. 3. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 3. 1. 1. 1. 2. 1. 1.
 1. 2. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 3. 1. 3. 1. 1. 1. 3. 2. 1. 1. 2. 1.
 1. 1. 1. 2. 1. 2. 1. 1. 1. 1. 1. 1. 3. 2. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1.
 1. 2. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 2. 3. 1. 1. 1. 1. 2. 2. 1. 1. 1. 3. 3. 1. 3. 1. 1. 3. 1. 1.
 2. 1. 1. 1. 2. 2. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 2. 1. 2. 1. 2. 1. 1. 3.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 2. 1. 2. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 2. 2. 2. 1. 1. 2. 2. 1. 1. 1. 1. 1. 1. 3. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 2. 1. 1. 1. 2. 1. 3. 1. 1. 3. 1. 2. 1. 1.
 3. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 2. 1. 1. 1. 1. 1.

[2. 1. 1. 2. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 2. 2. 3. 1. 1. 1. 1.
 1. 1. 2. 1. 2. 1. 2. 1. 3. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 2. 2. 2. 2. 1. 2. 1. 1. 3. 1. 1. 1. 1. 2. 1. 1. 1. 1. 2. 1. 3. 1. 1. 3.
 1. 1. 1. 1. 1. 1. 3. 1. 1. 1. 1. 2. 1. 2. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 2. 3. 1. 1. 1. 3. 2. 2. 1. 1. 2. 2.
 1. 1. 1. 1. 1. 1. 1. 3. 1. 1. 1. 1. 1. 1. 1. 1. 2. 1. 3. 1. 1. 1. 1. 1.
 3. 2. 1. 3. 1. 1. 1. 1. 1. 3. 1. 3. 1. 1. 1. 1. 1. 1. 2. 1. 3. 3. 1. 1.
 1. 1. 1. 1. 1. 3. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 2. 2. 1. 3. 1. 1. 1.
 1. 1. 3. 1. 1. 1. 1. 3. 2. 1. 1. 1. 1. 2. 1. 1. 1. 3. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 2. 3. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 3. 1. 1. 1. 1. 1.
 1. 1. 2. 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 2. 1.
 2. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 3. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 2. 1. 3. 2. 1. 1. 2. 1. 1. 1. 3. 1. 1. 2. 3. 1. 1. 2. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 2. 2. 1. 1. 1. 1. 1. 1. 1. 3. 1. 1. 1.

0.8802816901408451
-----
Split:  39
[2. 1. 1. 1. 1. 1. 1. 1. 1. 3. 1. 3. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 3. 1.
 2. 1. 1. 1. 1. 3. 1. 1. 1. 1. 3. 1. 1. 1. 2. 1. 1. 1. 1. 3. 2. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 3. 1. 1. 2. 1. 1. 1. 1. 1. 2.
 3. 1. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2.
 1. 1. 1. 1. 1. 1. 1. 2. 3. 1. 1. 1. 1. 1. 1. 1. 3. 1. 1. 1. 1. 2. 1. 1.
 1. 1. 1. 3. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 1. 3. 1. 2. 1. 1. 1. 1. 1. 1.
 2. 1. 1. 1. 1. 1. 1. 3. 1. 2. 1. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 3.
 3. 1. 1. 1. 2. 1. 3. 1. 2. 1. 1. 1. 1. 1. 1. 1. 1. 1. 3. 1. 1. 1. 1. 1.
 1. 2. 1. 1. 1. 1. 2. 2. 1. 3. 1. 1. 1. 2. 1. 1. 1. 1. 2. 2. 2. 1. 2. 1.
 1. 1. 3. 1. 1. 2. 1. 3. 1. 1. 3. 1. 1. 1. 1. 1. 3. 3. 1. 1. 1. 1. 3. 1.
 2. 1. 2. 3. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 2. 1. 2. 2. 1.
 2. 1. 1. 1. 2. 2. 1. 1. 1. 1. 3. 1. 1. 1. 3. 2. 1. 1. 1. 1. 1. 2. 1. 1.
 2. 1. 1. 1. 1. 1. 2. 1. 2. 3. 1. 1. 2. 1. 3. 1. 1. 1. 1. 1. 1. 1. 1. 2.
 2. 1. 1. 1. 1.

[1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 3. 1. 2. 1. 1. 2. 2. 1. 1. 3. 2. 2. 1. 1.
 1. 1. 1. 2. 1. 1. 1. 1. 1. 2. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 2. 3. 1. 1. 1. 1. 2. 1. 1. 2. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 3.
 1. 3. 1. 1. 1. 2. 1. 2. 1. 1. 1. 2. 3. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 3. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 2. 1. 1. 3. 3.
 3. 1. 2. 3. 1. 2. 3. 1. 1. 1. 1. 1. 3. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 2. 3. 1. 3. 1. 2. 1. 2. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 1. 1. 3. 1. 2.
 1. 1. 2. 1. 1. 1. 2. 3. 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 2. 1. 1. 2. 1. 1.
 2. 1. 1. 1. 1. 2. 2. 1. 3. 1. 1. 1. 1. 1. 3. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 3. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 2. 3. 1. 1.
 1. 1. 2. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 3. 1. 1.
 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 1. 2. 2. 1. 1. 3. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 2. 3. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1.
 1. 1. 1. 1. 2. 1. 2. 1. 1. 2. 1. 1. 1. 1. 1. 3. 1.

0.8873239436619719
-----
Split:  47
[1. 2. 1. 2. 3. 1. 1. 1. 1. 1. 1. 1. 2. 1. 3. 2. 1. 1. 2. 2. 1. 1. 1. 1.
 1. 3. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 2. 2. 3. 1. 2. 2. 1. 1. 1.
 2. 1. 1. 1. 1. 3. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 2. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 3. 1. 2. 2.
 1. 1. 1. 1. 3. 1. 1. 3. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 3. 1. 1. 1. 1. 1.
 1. 2. 1. 2. 1. 1. 1. 1. 1. 3. 1. 1. 2. 1. 1. 1. 1. 1. 1. 3. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 2. 1. 2. 1. 3. 1. 1. 1. 1. 1. 1. 2. 1. 1. 3. 3. 1. 1.
 1. 1. 1. 1. 1. 1. 2. 2. 1. 2. 1. 1. 1. 1. 1. 1. 3. 3. 1. 1. 3. 1. 1. 1.
 1. 1. 1. 2. 2. 3. 1. 1. 1. 1. 1. 1. 1. 1. 2. 1. 1. 2. 2. 1. 1. 3. 1. 1.
 1. 1. 1. 1. 3. 1. 1. 2. 1. 1. 1. 2. 1. 1. 3. 1. 1. 2. 1. 2. 1. 2. 2. 3.
 2. 1. 2. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1.
 1. 3. 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 3. 3. 1. 1. 1. 2. 1. 1. 1.
 2. 1. 1. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 3. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 2. 3. 1.

0.8943661971830986
-----
Split:  52
[1. 1. 3. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2.
 1. 1. 1. 1. 1. 1. 1. 3. 3. 1. 2. 1. 2. 1. 1. 1. 2. 3. 2. 1. 1. 1. 1. 1.
 3. 1. 1. 1. 1. 2. 1. 2. 2. 2. 1. 1. 1. 1. 1. 2. 2. 1. 1. 1. 1. 1. 2. 1.
 1. 1. 1. 1. 1. 2. 1. 3. 1. 1. 1. 1. 3. 1. 1. 1. 1. 2. 1. 1. 1. 1. 3. 1.
 1. 1. 1. 2. 1. 1. 1. 2. 2. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1.
 1. 1. 1. 3. 1. 3. 1. 3. 3. 1. 1. 1. 1. 2. 2. 1. 1. 1. 1. 1. 1. 1. 2. 1.
 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 1. 1. 3. 1. 2. 1. 1. 1. 1. 1. 1.
 1. 1. 2. 1. 1. 1. 3. 1. 1. 1. 1. 1. 1. 1. 1. 3. 1. 1. 1. 1. 3. 1. 1. 1.
 1. 1. 2. 1. 2. 1. 3. 1. 1. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 2.
 1. 3. 1. 1. 1. 1. 1. 3. 1. 1. 1. 3. 1. 1. 1. 1. 1. 3. 1. 1. 1. 1. 1. 2.
 2. 1. 3. 3. 2. 1. 1. 2. 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 1. 1. 3. 1.
 1. 1. 2. 1. 1. 1. 1. 1. 1. 2. 1. 1. 2. 1. 1. 3. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 2. 1. 1. 3. 1.
 2. 1. 1. 1. 1.

[2. 1. 1. 2. 1. 2. 2. 1. 1. 1. 1. 1. 1. 1. 3. 3. 1. 1. 1. 1. 1. 1. 2. 1.
 1. 2. 1. 1. 1. 3. 1. 2. 1. 1. 1. 1. 1. 1. 1. 1. 3. 1. 1. 1. 1. 1. 1. 1.
 1. 2. 1. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 2. 2. 1. 1. 1. 1. 1.
 2. 1. 1. 1. 3. 1. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 2.
 1. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 1. 3. 1. 1. 1. 1. 1. 2. 1.
 1. 1. 3. 2. 2. 2. 1. 1. 1. 3. 1. 1. 1. 1. 1. 2. 1. 2. 1. 1. 1. 1. 1. 3.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 3. 1. 3.
 2. 2. 2. 2. 1. 1. 1. 1. 1. 1. 3. 2. 1. 1. 3. 1. 1. 1. 2. 1. 1. 1. 1. 1.
 2. 1. 1. 1. 3. 1. 3. 1. 2. 1. 1. 1. 3. 2. 1. 1. 1. 2. 1. 1. 1. 1. 3. 1.
 1. 1. 1. 1. 1. 3. 1. 1. 1. 1. 1. 1. 1. 1. 1. 3. 1. 1. 1. 2. 1. 1. 3. 1.
 1. 1. 1. 3. 1. 1. 1. 1. 1. 2. 1. 3. 1. 1. 1. 3. 1. 1. 1. 3. 2. 1. 1. 1.
 2. 1. 3. 1. 1. 3. 1. 1. 1. 1. 1. 1. 1. 3. 1. 1. 1. 1. 1. 1. 1. 2. 1. 1.
 1. 1. 1. 2. 1. 1. 1. 3. 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 1.
 1. 3. 1. 1. 2. 2. 1. 1. 1. 1. 1. 1. 1. 1. 3. 1. 1.

[1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 2.
 3. 1. 1. 1. 1. 1. 1. 1. 1. 3. 1. 1. 1. 1. 2. 1. 1. 1. 1. 3. 1. 1. 1. 1.
 1. 1. 1. 1. 2. 1. 2. 2. 3. 1. 3. 1. 1. 2. 1. 1. 1. 3. 1. 2. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 3. 1. 2. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 3. 1.
 1. 1. 1. 1. 1. 1. 2. 2. 1. 1. 2. 1. 1. 3. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 2. 1. 2. 3. 1. 2. 1. 1. 3. 1. 1. 1. 2. 2. 2. 1. 1. 1.
 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 2. 1. 1. 2. 1. 1. 1. 3.
 3. 2. 2. 1. 3. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 1. 1.
 2. 1. 1. 1. 3. 1. 1. 1. 1. 1. 2. 3. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 2. 2. 1. 2. 1. 1. 1. 1. 1. 3. 1. 1. 1. 3. 1. 1. 1. 1. 1.
 2. 1. 1. 1. 1. 1. 3. 1. 1. 1. 1. 2. 2. 1. 1. 1. 2. 3. 1. 1. 1. 1. 1. 1.
 3. 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 2. 1. 1. 2. 3. 1. 1. 2. 1. 3. 1. 1. 1.
 2. 1. 2. 2. 1. 1. 1. 1. 1. 2. 1. 1. 3. 1. 1. 1. 1.

[1. 3. 1. 1. 3. 1. 1. 1. 1. 1. 3. 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 2. 1. 1. 2. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 2. 1. 1. 2. 1. 1.
 2. 1. 1. 1. 1. 1. 2. 1. 1. 1. 3. 1. 1. 1. 1. 2. 1. 1. 2. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 2. 1. 3. 1. 1. 1. 1. 1. 1. 3. 2. 1. 1. 2. 1. 2.
 1. 1. 2. 1. 1. 1. 2. 1. 1. 1. 1. 1. 2. 3. 1. 1. 1. 1. 1. 1. 1. 1. 2. 1.
 1. 2. 1. 1. 1. 1. 1. 2. 1. 1. 3. 1. 2. 1. 1. 1. 1. 1. 1. 3. 1. 1. 2. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 3. 2. 3. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 3. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 1. 3. 1. 1. 3. 2. 1.
 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 2. 1. 2. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2.
 2. 1. 1. 1. 1. 1. 1. 3. 1. 1. 3. 1. 2. 2. 3. 1. 1. 1. 1. 2. 1. 1. 1. 2.
 2. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 3. 1. 1. 2. 3. 1. 1. 1. 1. 1. 2. 1. 1.
 1. 3. 1. 1. 1. 1. 3. 1. 2. 1. 1. 1. 1. 1. 3. 1. 1. 1. 1. 1. 1. 2. 1. 2.
 1. 1. 1. 1. 1. 1. 3. 1. 1. 1. 1. 2. 1. 1. 2. 1. 1. 1. 2. 3. 1. 2. 1. 1.
 1. 3. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1.

 3. 1. 1. 1. 1. 1. 2. 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 3.]

Matriz de Confusión
[[315  20   1]
 [ 16  37   4]
 [  1   2  30]]
Precisión
0.8967136150234741
-----
Split:  71
[1. 1. 1. 1. 3. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 3. 3. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 3. 1. 1. 3. 1. 1. 2. 1. 1. 1. 1. 3. 1. 2. 1. 1. 1. 1. 1. 1. 2.
 1. 1. 1. 1. 1. 1. 1. 3. 1. 1. 1. 3. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 3. 2.
 1. 2. 1. 1. 1. 1. 1. 1. 1. 2. 1. 2. 2. 1. 3. 1. 1. 1. 3. 1. 1. 1. 1. 1.
 1. 1. 1. 3. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 1. 2. 1. 1. 2. 1. 1. 1. 1.
 1. 1. 1. 1. 3. 1. 1. 1. 1. 2. 1. 2. 2. 1. 1. 1. 2. 1. 1. 2. 1. 1. 1. 3.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 2. 1. 1. 1. 2. 2. 2. 1.
 1. 3. 1. 1. 3. 1. 2. 1. 1. 1. 1. 1. 1. 1. 3. 1. 1. 2. 1. 1. 2. 3. 2. 1.
 2. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 3. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 3. 1. 1. 1. 1. 3. 1.
 1. 1. 1. 1. 1. 1. 1. 3. 3. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 

0.9084507042253521
-----
Split:  76
[1. 1. 1. 1. 2. 1. 3. 1. 3. 2. 1. 1. 1. 3. 1. 3. 1. 1. 3. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 2. 1. 1. 2. 1. 1. 2. 1. 2. 1. 2. 1. 3. 2. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 3. 1. 1. 3. 1. 1. 1. 2. 1. 3.
 1. 1. 1. 1. 1. 2. 1. 2. 2. 2. 1. 3. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 2. 3. 1. 2. 3. 2. 1. 2. 1. 1. 2. 2. 1. 1. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1.
 1. 1. 1. 1. 2. 3. 1. 2. 2. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 3. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 2.
 2. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 2. 1. 1. 1. 1. 1. 1. 1. 2.
 1. 3. 1. 3. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 3. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 2. 1. 1. 2. 1. 1. 1. 1. 3. 1. 1. 2. 1. 3. 2. 1. 2. 3. 1. 1. 2.
 1. 1. 1. 2. 1. 1. 3. 1. 1. 1. 1. 1. 2. 3. 1. 2. 1. 1. 3. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 3. 2. 1. 3. 1. 1. 1. 2. 2. 3. 1. 1. 1.
 1. 2. 1. 1. 1. 1. 1. 1. 2. 1. 3. 1. 1. 1. 1. 1. 3. 2. 3. 1. 1. 2. 1. 1.
 3. 1. 3. 2. 2.

 2. 1. 1. 1. 1. 1. 1. 1. 2. 1. 3. 2. 1. 1. 1. 1. 2. 1.]
[1. 3. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 3. 1. 1. 1. 1. 1. 1. 1. 1. 1. 3. 3.
 1. 1. 3. 1. 1. 1. 1. 1. 1. 1. 1. 2. 3. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2.
 1. 1. 1. 2. 1. 1. 2. 1. 1. 1. 1. 2. 1. 1. 2. 1. 2. 1. 1. 1. 2. 1. 1. 1.
 1. 1. 1. 1. 1. 3. 2. 1. 3. 1. 1. 1. 1. 1. 1. 3. 1. 1. 1. 3. 1. 1. 1. 1.
 1. 1. 1. 1. 3. 1. 2. 2. 1. 3. 1. 1. 1. 1. 1. 2. 3. 3. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 1. 1. 3. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 3. 1. 1. 2. 1. 1. 1.
 1. 3. 1. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 3. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 3. 1. 1. 3. 1. 1. 1. 1. 3. 1. 1. 2. 1. 2. 1. 3. 1. 1. 1. 3. 1.
 1. 1. 1. 1. 3. 1. 2. 2. 1. 1. 2. 3. 1. 2. 1. 1. 2. 1. 1. 1. 1. 2. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 3. 1. 1. 2.
 1. 1. 2. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 2. 1. 1. 1. 1.
 2. 1. 1. 3. 3. 3. 1. 1. 1. 1. 3. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1

[1. 1. 1. 3. 1. 1. 1. 1. 1. 1. 2. 2. 2. 1. 2. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 2.
 2. 1. 1. 3. 1. 3. 1. 1. 3. 2. 1. 2. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 2. 1. 1. 2. 1. 3. 2. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1.
 1. 3. 1. 1. 3. 2. 3. 1. 2. 3. 1. 1. 3. 2. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 3. 2. 1. 1. 3. 3. 1. 1. 1. 2. 1. 1. 1. 1. 1. 3. 1. 1. 1.
 3. 1. 1. 2. 1. 2. 2. 1. 1. 1. 1. 1. 3. 1. 2. 3. 1. 1. 1. 1. 2. 1. 1. 1.
 1. 1. 1. 2. 2. 1. 1. 3. 1. 2. 2. 1. 1. 1. 2. 1. 3. 1. 1. 1. 1. 1. 1. 2.
 2. 1. 1. 1. 1. 1. 1. 2. 1. 3. 1. 1. 1. 3. 2. 1. 1. 1. 1. 1. 1. 1. 1. 3.
 1. 2. 1. 3. 1. 1. 1. 2. 2. 1. 3. 1. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 2.
 3. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 1. 2. 1. 1. 1. 2. 1. 1. 3. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 2. 1. 3. 2. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 2.
 3. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1.

[1. 1. 3. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 3. 1. 1. 3. 1.
 1. 1. 1. 2. 1. 2. 1. 2. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 3. 1. 1. 3.
 1. 1. 1. 3. 1. 1. 1. 2. 2. 1. 2. 1. 1. 1. 1. 1. 1. 1. 1. 2. 1. 3. 1. 2.
 1. 1. 2. 1. 1. 1. 2. 3. 2. 1. 2. 1. 1. 3. 1. 3. 1. 2. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 1. 2. 1. 1. 1. 1. 1. 1. 1. 1. 3. 1.
 2. 1. 1. 1. 1. 1. 1. 1. 1. 2. 1. 1. 2. 3. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 2. 1. 1. 1. 1.
 3. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 1. 2. 1. 3. 2. 1. 1. 1. 3. 1. 1. 1. 3.
 2. 3. 2. 1. 1. 1. 3. 1. 1. 3. 1. 3. 2. 1. 3. 1. 1. 3. 1. 1. 1. 1. 1. 2.
 1. 2. 1. 1. 1. 1. 1. 1. 3. 2. 1. 1. 2. 1. 1. 1. 1. 1. 1. 3. 2. 1. 1. 1.
 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 3. 1. 1. 1. 1. 2. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 3. 1. 1. 1. 2. 1. 2. 1. 1. 1. 1. 1. 1. 1. 1. 2.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 1.
 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 2. 1. 2. 1. 1. 1. 2.

 1. 1. 2. 1. 1. 1. 2. 1. 1. 3. 3. 1. 1. 3. 1. 1. 1. 2.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 3. 2. 2. 2. 3. 1. 1. 1. 1. 1. 1. 2. 1.
 1. 1. 1. 1. 1. 1. 2. 1. 1. 2. 2. 2. 1. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1.
 3. 1. 1. 2. 1. 2. 1. 1. 1. 1. 1. 2. 1. 1. 2. 2. 1. 2. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 3. 1. 3. 2. 1. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 1.
 1. 2. 3. 1. 2. 2. 1. 2. 1. 1. 2. 1. 1. 2. 1. 1. 1. 1. 1. 2. 1. 2. 1. 1.
 1. 2. 1. 2. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 3. 2. 1. 1. 1. 1. 2. 1. 2.
 1. 1. 1. 1. 2. 3. 2. 2. 1. 1. 2. 3. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 3. 1.
 3. 3. 1. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 2. 1. 1. 1. 2. 1. 1. 2. 1.
 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 1. 1. 3. 1. 2. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 2. 2. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 2. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 2. 2. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 1. 3. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 3. 2. 1. 3. 1. 2. 1. 1. 1. 1. 2. 1. 1. 1.
 1. 2. 1. 1. 1. 1. 1. 2. 1. 3. 1. 1. 2. 1. 1. 1. 1. 1. 1. 2. 1. 1. 3

 1. 2. 1. 2. 1. 3. 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[1. 1. 1. 1. 3. 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 2. 1. 1. 1. 2. 3. 1. 1. 1. 3. 1. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 2. 1. 1. 1. 1. 2. 1. 1. 1. 1. 1.
 1. 1. 3. 3. 1. 1. 1. 1. 2. 1. 1. 1. 1. 2. 1. 1. 2. 1. 1. 1. 1. 1. 1. 1.
 1. 2. 1. 1. 1. 1. 2. 1. 2. 1. 1. 1. 1. 1. 1. 2. 3. 1. 1. 1. 1. 2. 1. 1.
 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 3. 1. 1. 3. 1. 1. 2. 1. 1. 1. 1. 1. 3. 1. 1. 2. 1. 2.
 1. 1. 1. 1. 1. 2. 1. 3. 1. 1. 1. 1. 1. 1. 3. 1. 2. 1. 1. 1. 2. 3. 1. 1.
 3. 2. 1. 2. 2. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 2. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 2. 1. 2. 1. 1. 2. 1. 1. 1. 1.
 1. 1. 3. 3. 1. 1. 1. 1. 2. 2. 2. 2. 1. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1.
 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 3. 1. 1. 1. 1

In [6]:
    print("==================================================")
    print("Confiabidad 80(train)/20(test)    :             | ")
    print("==================================================")
    print(np.median(confiabilidad1))
    print("==================================================")

Confiabidad 80(train)/20(test)    :             | 
0.8943661971830986


In [7]:
shufflesplit=StratifiedShuffleSplit(n_splits=100, test_size=0.50, random_state=0)
cv=shufflesplit.split(X,Y)
confiabilidad=np.zeros(100)
for indice, (train_index, test_index) in enumerate( cv):
    print("-----")
    print("Split: ",indice)
    clasificador.fit(X[train_index],Y[train_index])
    y_obtenido = clasificador.predict(X[test_index])
    print(Y[test_index])
    print(y_obtenido)
    print("")
    print("Matriz de Confusión")
    print(confusion_matrix(y_obtenido,Y[test_index]))
    print("Precisión")
    c1=precision_score(y_obtenido, Y[test_index], average='micro')
    print(c1)
    confiabilidad2[indice]=c1
    

-----
Split:  0
[1. 1. 1. ... 1. 1. 1.]
[1. 1. 1. ... 1. 2. 1.]

Matriz de Confusión
[[764  39   6]
 [ 58  94  14]
 [  6  14  68]]
Precisión
0.8711194731890874
-----
Split:  1
[1. 1. 1. ... 1. 1. 1.]
[1. 1. 2. ... 1. 1. 1.]

Matriz de Confusión
[[762  36  12]
 [ 54  97   5]
 [ 12  14  71]]
Precisión
0.8748824082784572
-----
Split:  2
[1. 1. 1. ... 1. 1. 1.]
[1. 1. 1. ... 1. 1. 1.]

Matriz de Confusión
[[786  43   8]
 [ 39  99  13]
 [  2   6  67]]
Precisión
0.8955785512699906
-----
Split:  3
[1. 1. 1. ... 1. 1. 1.]
[1. 1. 1. ... 1. 1. 1.]

Matriz de Confusión
[[786  39   5]
 [ 36  97  14]
 [  5  12  69]]
Precisión
0.8955785512699906
-----
Split:  4
[2. 1. 1. ... 1. 1. 1.]
[2. 2. 1. ... 1. 1. 1.]

Matriz de Confusión
[[785  59   5]
 [ 34  83  20]
 [  9   5  63]]
Precisión
0.8758231420507996
-----
Split:  5
[2. 1. 2. ... 1. 1. 1.]
[2. 1. 3. ... 1. 1. 1.]

Matriz de Confusión
[[769  45  11]
 [ 54  94  18]
 [  5   8  59]]
Precisión
0.8673565380997178
-----
Split:  6
[1. 1. 1. ... 1. 1. 1.]


[[788  45  13]
 [ 32  91  10]
 [  8  11  65]]
Precisión
0.8880526810912511
-----
Split:  58
[1. 2. 1. ... 1. 2. 1.]
[1. 1. 2. ... 1. 1. 1.]

Matriz de Confusión
[[775  57  15]
 [ 43  82  12]
 [  9   9  61]]
Precisión
0.863593603010348
-----
Split:  59
[2. 1. 1. ... 1. 3. 1.]
[2. 1. 1. ... 1. 2. 1.]

Matriz de Confusión
[[782  36   6]
 [ 34 104  11]
 [ 12   7  71]]
Precisión
0.9002822201317028
-----
Split:  60
[1. 1. 1. ... 1. 2. 1.]
[1. 1. 2. ... 1. 2. 1.]

Matriz de Confusión
[[768  52  11]
 [ 49  91  14]
 [ 10   5  63]]
Precisión
0.8673565380997178
-----
Split:  61
[1. 1. 1. ... 1. 2. 3.]
[1. 1. 1. ... 1. 2. 3.]

Matriz de Confusión
[[784  45   6]
 [ 31  93  12]
 [ 12  10  70]]
Precisión
0.8908748824082785
-----
Split:  62
[1. 1. 1. ... 1. 1. 2.]
[1. 1. 1. ... 1. 1. 1.]

Matriz de Confusión
[[774  46  14]
 [ 44  95  13]
 [ 10   6  61]]
Precisión
0.8748824082784572
-----
Split:  63
[2. 1. 2. ... 1. 2. 2.]
[1. 1. 2. ... 1. 2. 1.]

Matriz de Confusión
[[785  54   7]
 [ 29  87  17]
 [ 13

In [8]:
print("==================================================")
print("Confiabidad 50(train)/50(test)    :             | ")
print("==================================================")
print(np.median(confiabilidad2))
print("==================================================")

Confiabidad 50(train)/50(test)    :             | 
0.8809971777986829
