# Primer código

Descripción del objetivo

Campos del dataset

1 Primera Ejecución

In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

#Leyendo el archivo CSV
data= pd.read_csv("fetal_health.csv", sep=",", header=[0])
print(data.describe())
X = data.iloc[:, :-1].values
print(X[0])
Y = data.iloc[:,21].values
print(Y)

from sklearn.impute import SimpleImputer
from sklearn import preprocessing

#Preprosesamiento 1, rellenar con la media los espacios faltantes

imputer = SimpleImputer(missing_values=np.NaN, strategy='mean')
imputer = imputer.fit(X)
X= imputer.transform(X)

#Preprosesamiento 2, normalizar los datos

X=preprocessing.normalize(X)
#print(X)

from sklearn.model_selection import StratifiedShuffleSplit
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import confusion_matrix
from sklearn.metrics import precision_score

clasificador=MLPClassifier(hidden_layer_sizes=(128, 64, 32), solver='adam',max_iter=1000)
clasificador.fit(X,Y)
y_obtenido=clasificador.predict(X)
matriz=confusion_matrix(y_obtenido,Y)

print("==================================================")
print("Matriz de confusión :                             | ")
print("==================================================")
print(matriz)

print("==================================================")
print("Precisión           :                            | ")
print("==================================================")
print(precision_score(y_obtenido,Y,average='micro'))
print("==================================================")

print("==================================================")
print("Splits             :                            | ")
print("==================================================")

shufflesplit=StratifiedShuffleSplit(n_splits=100, test_size=0.20, random_state=0)
cv=shufflesplit.split(X,Y)
confiabilidad=np.zeros(100)
for indice, (train_index, test_index) in enumerate( cv):
    print("-----")
    print("Split: ",indice)
    clasificador.fit(X[train_index],Y[train_index])
    y_obtenido = clasificador.predict(X[test_index])
    print(Y[test_index])
    print(y_obtenido)
    print("")
    print("Matriz de Confusión")
    print(confusion_matrix(y_obtenido,Y[test_index]))
    print("Precisión")
    c1=precision_score(y_obtenido, Y[test_index], average='micro')
    print(c1)
    confiabilidad[indice]=c1
    


       baseline value  accelerations  fetal_movement  uterine_contractions  \
count     2126.000000    2126.000000     2126.000000           2126.000000   
mean       133.303857       0.003178        0.009481              0.004366   
std          9.840844       0.003866        0.046666              0.002946   
min        106.000000       0.000000        0.000000              0.000000   
25%        126.000000       0.000000        0.000000              0.002000   
50%        133.000000       0.002000        0.000000              0.004000   
75%        140.000000       0.006000        0.003000              0.007000   
max        160.000000       0.019000        0.481000              0.015000   

       light_decelerations  severe_decelerations  prolongued_decelerations  \
count          2126.000000           2126.000000               2126.000000   
mean              0.001889              0.000003                  0.000159   
std               0.002960              0.000057               

[1. 2. 1. 1. 1. 1. 2. 2. 1. 1. 1. 1. 1. 3. 1. 2. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 2. 3. 1. 1. 1. 2. 1.
 1. 1. 1. 1. 2. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 1. 3. 1. 1. 1. 2. 1. 1.
 1. 1. 1. 1. 2. 2. 1. 2. 3. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 3.
 1. 1. 1. 2. 2. 1. 2. 1. 1. 3. 1. 3. 3. 1. 1. 1. 1. 1. 1. 1. 1. 1. 3. 1.
 1. 1. 2. 1. 2. 3. 1. 1. 1. 2. 3. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 1. 1.
 3. 1. 2. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 3. 1. 2. 3. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 2. 1. 3. 1. 1. 1. 2. 1. 1. 3. 1. 1. 1. 1. 1. 1. 1.
 1. 3. 1. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 3. 1. 1. 2. 1. 1. 1.
 1. 1. 1. 3. 1. 2. 1. 1. 1. 1. 1. 1. 3. 2. 2. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 2. 1. 1. 1. 1. 1. 3. 2. 1. 1. 1. 1.
 1. 1. 1. 1. 2. 1. 2. 1. 1. 1. 1. 1. 1. 1. 2. 1. 2. 2. 1. 1. 1. 3. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 2. 1. 1. 1. 1. 1. 1. 1. 1. 1. 3. 1. 3.
 1. 1. 1. 1. 1. 2. 3. 2. 1. 2. 2. 1. 1. 2. 3. 1. 1.

[1. 1. 1. 1. 2. 2. 3. 2. 1. 1. 1. 1. 1. 2. 1. 1. 3. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 2. 1. 1. 1. 1. 3. 1. 1. 1. 1. 1. 1. 2. 1. 1. 3. 2. 1. 2. 1. 2.
 1. 1. 1. 2. 3. 1. 1. 1. 1. 1. 2. 3. 2. 1. 3. 3. 1. 2. 2. 2. 1. 1. 1. 2.
 1. 1. 1. 1. 1. 3. 1. 2. 1. 2. 1. 1. 1. 1. 2. 3. 2. 1. 2. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 3. 1. 1. 3. 2. 1. 3. 1. 1. 1. 3. 1. 2. 1. 1. 1. 1. 2. 1.
 1. 1. 2. 1. 3. 1. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 1.
 1. 2. 1. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 2. 1. 2. 1. 1. 1. 1. 3. 1. 1. 1.
 2. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 1. 2. 1. 2.
 2. 1. 1. 1. 1. 1. 2. 1. 1. 1. 3. 1. 3. 2. 1. 1. 1. 1. 2. 1. 1. 2. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 2. 1. 2. 2. 1. 1. 1. 1. 3. 1. 1. 1. 1. 1. 1. 1. 3.
 1. 3. 1. 1. 1. 1. 1. 1. 1. 1. 3. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 3. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 3. 2. 1. 3. 1. 1.

[1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2.
 2. 1. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 2. 2. 1. 1. 1.
 1. 1. 1. 1. 2. 1. 1. 2. 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 2. 2. 1. 2. 1. 1.
 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 3. 1. 1.
 1. 2. 1. 1. 1. 1. 1. 2. 1. 2. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 3.
 1. 1. 2. 1. 1. 1. 1. 2. 1. 2. 1. 1. 3. 2. 3. 2. 1. 3. 3. 1. 1. 3. 1. 1.
 3. 3. 3. 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 1. 3. 1.
 1. 1. 3. 1. 1. 1. 1. 2. 1. 2. 2. 2. 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 2. 1. 2. 1. 3. 1. 1. 2. 1. 1. 1. 1. 1. 1. 2. 1. 1. 3. 1. 1. 2. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 3. 3. 1. 1. 1. 3. 1. 2. 1. 1. 1.
 3. 1. 1. 1. 3. 1. 3. 1. 2. 1. 2. 1. 1. 1. 1. 1. 1. 1. 1. 1. 3. 1. 1. 2.
 1. 1. 1. 1. 1. 3. 1. 1. 1. 1. 1. 2. 1. 1. 1. 3. 1. 1. 3. 1. 2. 1. 1. 1.
 3. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 3. 1. 1. 1.

[1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 2. 1. 1.
 2. 1. 2. 2. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 2. 1. 2. 1. 1. 1. 1. 1.
 1. 2. 1. 1. 1. 1. 1. 2. 1. 3. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 1.
 3. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 2. 1. 2. 2. 1. 1. 1.
 3. 1. 2. 3. 1. 1. 2. 1. 1. 1. 2. 1. 2. 3. 2. 1. 1. 1. 1. 3. 1. 1. 3. 3.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 1. 1. 3. 1. 1. 1. 1. 1.
 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 3. 1. 3. 3. 1. 1. 1. 1. 1. 1. 1.
 1. 3. 1. 1. 1. 1. 3. 1. 1. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 2. 1. 3. 1. 1.
 2. 1. 3. 1. 1. 2. 1. 2. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 1. 1.
 1. 3. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 2. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 1.
 2. 1. 1. 1. 2. 1. 3. 1. 1. 1. 1. 1. 2. 1. 1. 2. 1. 1. 1. 1. 3. 1. 1. 1.
 2. 1. 1. 1. 1. 1. 1. 1. 3. 1. 2. 3. 2. 1. 1. 1. 1. 1. 2. 2. 1. 3. 1. 1.
 2. 1. 2. 2. 1. 1. 1. 2. 1. 1. 1. 1. 3. 1. 3. 1. 1.

[1. 1. 1. 1. 1. 1. 3. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 3. 1. 3. 1. 2.
 1. 2. 1. 3. 2. 1. 2. 1. 1. 1. 1. 1. 1. 1. 1. 1. 3. 1. 1. 1. 1. 1. 1. 1.
 3. 1. 1. 1. 3. 2. 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 1.
 1. 2. 1. 3. 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1.
 1. 1. 1. 1. 1. 2. 1. 1. 2. 1. 2. 1. 1. 1. 1. 1. 1. 1. 2. 1. 2. 3. 1. 1.
 1. 2. 1. 1. 3. 3. 1. 1. 1. 1. 1. 1. 2. 1. 2. 3. 1. 1. 1. 2. 1. 3. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 3.
 1. 2. 1. 1. 2. 1. 1. 1. 1. 2. 2. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 2.
 1. 3. 1. 1. 1. 1. 1. 1. 3. 1. 3. 1. 1. 2. 3. 1. 2. 1. 3. 2. 2. 1. 1. 1.
 1. 1. 1. 2. 1. 1. 1. 1. 2. 1. 1. 1. 1. 2. 1. 1. 1. 2. 1. 2. 1. 1. 1. 1.
 3. 1. 2. 1. 1. 1. 2. 2. 1. 1. 1. 1. 1. 1. 3. 1. 1. 1. 1. 2. 1. 2. 1. 1.
 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 3. 1. 3. 1. 1. 3. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2.
 2. 1. 1. 1. 1. 3. 1. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1.

[3. 1. 1. 1. 1. 1. 2. 1. 1. 1. 2. 1. 3. 1. 1. 2. 1. 1. 1. 1. 1. 3. 1. 1.
 2. 1. 1. 1. 1. 1. 1. 3. 1. 1. 1. 1. 1. 1. 1. 1. 3. 1. 1. 1. 1. 2. 2. 1.
 1. 2. 1. 2. 1. 1. 2. 1. 3. 1. 2. 1. 1. 1. 3. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 2. 3. 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 2. 2. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 2. 2. 1. 3. 1. 2. 1. 1. 1. 1. 1. 1. 1. 2.
 1. 1. 1. 1. 2. 2. 1. 3. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 2. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 3. 1. 1. 1. 1. 1. 1. 2. 1. 2. 1. 1.
 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 1. 1. 3. 1. 1. 1. 2. 1. 1. 1. 1. 1. 3. 3.
 1. 1. 1. 3. 2. 1. 3. 1. 1. 1. 1. 1. 1. 1. 2. 1. 2. 1. 1. 1. 1. 1. 1. 1.
 1. 2. 1. 1. 1. 2. 2. 3. 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1.
 1. 3. 1. 1. 2. 1. 1. 1. 1. 2. 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 1. 2. 3. 1.
 1. 2. 1. 1. 1. 1. 1. 3. 1. 2. 1. 2. 1. 1. 1. 1. 1. 1. 3. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 3. 1. 1. 1. 1. 1. 3. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 3. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.

[1. 1. 1. 1. 3. 1. 1. 1. 1. 3. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 1. 2. 1. 2.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 3. 1. 1. 1. 1. 1. 1. 1. 2. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 3. 2. 1. 1. 1. 1. 2. 1. 1. 3. 2. 1. 3.
 1. 3. 2. 3. 1. 1. 1. 1. 3. 1. 3. 3. 1. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1.
 2. 1. 1. 1. 1. 1. 1. 1. 1. 2. 1. 1. 2. 1. 1. 3. 1. 2. 1. 1. 1. 1. 1. 2.
 3. 1. 3. 1. 1. 1. 2. 3. 1. 3. 1. 1. 2. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 1.
 1. 3. 1. 1. 1. 1. 1. 1. 2. 1. 1. 2. 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 3. 2. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 1.
 1. 1. 1. 2. 3. 1. 1. 1. 2. 1. 2. 1. 1. 3. 1. 1. 1. 1. 2. 3. 1. 1. 2. 2.
 1. 1. 1. 1. 1. 1. 1. 1. 2. 1. 3. 1. 1. 3. 1. 1. 1. 1. 2. 3. 1. 1. 1. 1.
 2. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 2. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 2. 1. 1. 1. 1. 1. 1. 3. 2. 1. 1. 1. 1. 1. 1. 3. 1. 1. 1. 1. 2. 1. 1. 1.
 2. 1. 1. 1. 1. 1. 1. 1. 1. 3. 1. 1. 1. 1. 1. 1. 3. 3. 2. 1. 1. 2. 1. 2.
 2. 1. 1. 1. 1. 2. 2. 1. 1. 1. 1. 1. 1. 2. 2. 1. 1.

[2. 3. 1. 3. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 1. 1. 3.
 1. 1. 1. 1. 3. 1. 1. 2. 1. 3. 2. 3. 1. 1. 1. 1. 1. 2. 1. 1. 1. 3. 1. 1.
 1. 1. 1. 2. 1. 2. 1. 1. 2. 1. 2. 1. 2. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 1. 2. 1. 1.
 1. 1. 1. 1. 1. 1. 2. 3. 1. 1. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 3. 1.
 1. 1. 1. 1. 1. 1. 1. 2. 1. 1. 3. 1. 1. 1. 2. 1. 2. 1. 3. 2. 2. 3. 2. 1.
 1. 1. 1. 2. 1. 1. 2. 1. 1. 3. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 3. 1. 2. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 3. 1. 1. 1. 1. 1. 1. 1. 1. 2. 1. 2. 2. 1. 1.
 1. 1. 1. 1. 2. 1. 2. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 3. 1. 1. 1. 1. 1. 1. 1. 1. 3. 3. 1. 3. 1. 2. 1. 3. 1.
 2. 2. 2. 2. 2. 1. 3. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1.
 1. 1. 1. 1. 2. 3. 1. 1. 3. 3. 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 3. 1. 1. 1.
 1. 1. 2. 2. 2. 1. 3. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.

[2. 1. 1. 2. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 2. 2. 3. 1. 1. 1. 1.
 1. 1. 2. 1. 2. 1. 2. 1. 3. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 2. 2. 2. 2. 1. 2. 1. 1. 3. 1. 1. 1. 1. 2. 1. 1. 1. 1. 2. 1. 3. 1. 1. 3.
 1. 1. 1. 1. 1. 1. 3. 1. 1. 1. 1. 2. 1. 2. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 2. 3. 1. 1. 1. 3. 2. 2. 1. 1. 2. 2.
 1. 1. 1. 1. 1. 1. 1. 3. 1. 1. 1. 1. 1. 1. 1. 1. 2. 1. 3. 1. 1. 1. 1. 1.
 3. 2. 1. 3. 1. 1. 1. 1. 1. 3. 1. 3. 1. 1. 1. 1. 1. 1. 2. 1. 3. 3. 1. 1.
 1. 1. 1. 1. 1. 3. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 2. 2. 1. 3. 1. 1. 1.
 1. 1. 3. 1. 1. 1. 1. 3. 2. 1. 1. 1. 1. 2. 1. 1. 1. 3. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 2. 3. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 3. 1. 1. 1. 1. 1.
 1. 1. 2. 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 2. 1.
 2. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 3. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 2. 1. 3. 2. 1. 1. 2. 1. 1. 1. 3. 1. 1. 2. 3. 1. 1. 2. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 2. 2. 1. 1. 1. 1. 1. 1. 1. 3. 1. 1. 1.

[1. 1. 1. 1. 2. 2. 1. 1. 2. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 3. 1. 1. 1.
 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 2. 1. 2. 1. 1. 3. 2. 3. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 2. 1. 2. 1. 1. 1. 1. 1. 1. 3. 3. 1. 2. 1.
 1. 2. 1. 1. 2. 2. 1. 1. 1. 1. 1. 3. 1. 1. 1. 1. 3. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 2. 1. 1. 1. 3. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 1. 1. 3. 1. 2. 1.
 1. 1. 1. 1. 1. 1. 2. 1. 1. 2. 1. 2. 2. 1. 1. 1. 3. 1. 1. 2. 1. 1. 1. 1.
 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 3. 2. 1. 1. 3. 2. 1. 1. 3. 1. 1. 1. 2.
 3. 2. 1. 1. 1. 3. 3. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 1.
 1. 1. 2. 1. 1. 1. 1. 1. 3. 1. 1. 1. 1. 1. 3. 1. 3. 2. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 2. 2. 1. 1.
 1. 2. 1. 3. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 3. 3. 3. 1.
 1. 1. 1. 1. 1. 1. 3. 1. 1. 1. 1. 1. 1. 1. 3. 2. 1.

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 2. 1. 3. 1. 1. 1. 1.
 1. 1. 1. 2. 1. 1. 1. 3. 2. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 3. 1. 2. 1. 2. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 2. 1. 1. 3. 1.
 1. 2. 1. 1. 1. 1. 1. 3. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 2. 1. 1. 1. 1. 2. 1. 1. 3. 1. 1. 1. 1. 1. 2. 1. 1. 1. 2. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 3. 1. 1. 1. 3. 1. 1. 2. 2. 1. 1. 1. 1. 1. 1. 3. 2. 1. 1.
 1. 3. 1. 1. 1. 3. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 3. 1. 1. 1. 1. 1. 1. 1.
 1. 3. 2. 3. 1. 1. 3. 1. 2. 1. 3. 1. 1. 1. 2. 1. 1. 1. 1. 3. 1. 1. 1. 1.
 1. 3. 1. 1. 3. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 2. 1. 1. 1. 1. 3. 1. 1. 3.
 1. 1. 1. 1. 2. 1. 1. 1. 3. 2. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 2. 1. 2. 1.
 3. 1. 1. 2. 1. 1. 3. 2. 1. 1. 2. 1. 3. 2. 1. 1. 1. 1. 2. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 2. 1. 2. 1. 1. 2. 1. 1. 1. 1. 1. 1. 2. 1. 1. 2. 1. 1. 2. 1.
 3. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 3. 1. 2. 1. 2.

[1. 3. 1. 1. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 3. 1. 2.
 1. 3. 1. 1. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 1.
 1. 1. 3. 2. 1. 1. 2. 2. 1. 2. 1. 1. 1. 1. 1. 1. 2. 1. 3. 2. 1. 3. 1. 1.
 1. 3. 1. 1. 1. 1. 1. 2. 1. 1. 3. 3. 1. 1. 1. 1. 1. 1. 1. 1. 3. 3. 1. 2.
 1. 3. 1. 1. 3. 1. 2. 1. 1. 2. 1. 2. 2. 1. 1. 1. 1. 1. 1. 1. 1. 2. 1. 1.
 1. 1. 1. 1. 3. 1. 2. 1. 1. 1. 1. 1. 1. 1. 2. 1. 2. 2. 1. 1. 1. 1. 2. 1.
 1. 2. 1. 2. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 3. 1. 1. 1. 1. 1. 1.
 2. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 2. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 3. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 2. 1. 1. 2. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 1.
 1. 3. 1. 3. 1. 2. 1. 1. 3. 1. 1. 2. 2. 1. 2. 1. 1. 2. 1. 1. 1. 2. 1. 2.
 1. 1. 3. 1. 1. 1. 1. 1. 1. 1. 1. 3. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 3. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 1. 3. 1. 1. 1. 2.
 3. 1. 1. 1. 1. 1. 1. 2. 1. 1. 2. 1. 1. 1. 2. 1. 3.

[1. 1. 1. 1. 1. 1. 3. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 1. 1. 3. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2.
 1. 1. 1. 3. 1. 1. 1. 1. 1. 3. 2. 1. 1. 2. 1. 1. 1. 1. 1. 2. 3. 2. 1. 2.
 1. 1. 1. 2. 3. 1. 1. 1. 1. 2. 1. 1. 1. 2. 2. 3. 1. 1. 1. 1. 1. 2. 1. 1.
 1. 1. 1. 2. 1. 1. 1. 3. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 2. 1. 1. 1. 1. 2. 1. 1. 2. 1. 3. 2. 1. 1. 1. 1. 3. 1. 1. 2. 3. 1. 2. 1.
 2. 1. 2. 2. 1. 1. 1. 1. 1. 1. 2. 1. 3. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 3. 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 1. 1. 3. 1. 1.
 2. 2. 1. 1. 3. 2. 1. 1. 2. 1. 1. 1. 1. 2. 1. 3. 1. 1. 3. 2. 1. 1. 1. 1.
 2. 1. 3. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 3. 2. 1. 1. 1. 2. 1.
 1. 1. 1. 3. 1. 1. 1. 1. 2. 1. 1. 1. 3. 1. 1. 1. 1. 1. 1. 1. 1. 2. 3. 1.
 1. 2. 2. 3. 1. 1. 1. 1. 1. 2. 1. 1. 3. 1. 1. 1. 3. 1. 1. 1. 1. 3. 1. 1.
 1. 1. 3. 3. 2. 1. 1. 1. 1. 1. 1. 1. 2. 2. 1. 1. 1. 1. 1. 1. 1. 2. 2. 1.
 1. 2. 1. 1. 1. 2. 2. 1. 1. 1. 3. 1. 1. 1. 1. 1. 1.

[2. 1. 1. 2. 2. 1. 1. 1. 1. 1. 1. 1. 2. 2. 1. 1. 1. 1. 1. 1. 1. 1. 3. 3.
 1. 2. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 1. 1. 2. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 3. 1. 1. 2. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 2. 2. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 3. 1. 1. 3. 1. 1. 1. 1. 1. 1. 1. 1. 1. 3. 3. 1. 1.
 1. 1. 3. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 3. 1. 1. 1. 1. 1. 2. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 2. 2. 1. 1. 2. 2. 1. 1. 1. 1. 2. 1. 1. 2. 1. 1. 1. 1.
 2. 1. 1. 1. 2. 1. 3. 1. 1. 1. 1. 1. 1. 2. 1. 1. 3. 1. 2. 1. 2. 1. 2. 1.
 1. 2. 1. 3. 2. 1. 1. 3. 1. 2. 1. 1. 1. 1. 1. 1. 1. 1. 2. 1. 3. 1. 1. 1.
 1. 3. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 1. 3. 3. 1. 3. 1. 1. 1.
 2. 1. 3. 1. 1. 1. 3. 1. 1. 1. 2. 1. 2. 1. 1. 1. 2. 1. 3. 1. 1. 1. 1. 3.
 3. 1. 1. 1. 3. 1. 1. 1. 1. 1. 1. 1. 1. 2. 2. 1. 1. 1. 1. 2. 1. 1. 2. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 3. 2. 1. 1. 1. 1. 1. 1. 2.
 3. 1. 1. 1. 2. 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 2. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 1. 2. 1. 1.

[1. 1. 1. 1. 1. 1. 1. 1. 2. 2. 1. 2. 1. 1. 3. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 1. 1. 3. 1. 1.
 1. 1. 3. 2. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 1. 1. 2. 1. 2. 1. 3. 1. 3.
 1. 1. 1. 1. 1. 1. 2. 3. 2. 2. 3. 1. 1. 1. 1. 1. 1. 1. 3. 1. 1. 1. 1. 1.
 3. 1. 1. 1. 1. 2. 1. 1. 1. 1. 3. 1. 1. 2. 1. 1. 1. 1. 3. 1. 1. 1. 2. 1.
 1. 1. 2. 3. 1. 1. 1. 2. 1. 1. 3. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 2. 1. 1. 1. 1. 1. 1. 1. 3. 1. 1.
 1. 2. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 3. 1. 1. 1. 3. 1. 1.
 1. 1. 1. 1. 1. 3. 3. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 3. 1.
 1. 1. 1. 1. 3. 1. 3. 3. 1. 1. 2. 3. 1. 2. 2. 1. 2. 1. 1. 1. 1. 1. 2. 1.
 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 1.
 1. 2. 3. 1. 1. 2. 1. 1. 3. 3. 2. 2. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 1.
 1. 1. 1. 1. 1. 1. 3. 1. 1. 3. 3. 2. 1. 1. 1. 2. 1. 2. 1. 2. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 1. 2.

[1. 1. 1. 1. 1. 1. 1. 3. 1. 2. 2. 2. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 2. 1. 1. 1. 2. 1. 1. 2. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 1. 2. 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 3. 1. 1. 1. 1. 1. 1. 1. 1. 2. 1. 1. 3. 1. 1. 1. 1. 1. 1. 1. 3. 1. 1.
 1. 1. 1. 1. 3. 3. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 3. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 2. 2. 2. 1. 1. 1. 1. 1. 3.
 3. 1. 1. 1. 1. 3. 1. 1. 1. 1. 1. 3. 1. 1. 1. 1. 1. 1. 1. 2. 1. 3. 1. 1.
 1. 1. 1. 1. 1. 3. 1. 2. 1. 2. 1. 1. 1. 1. 1. 3. 1. 1. 2. 1. 1. 1. 3. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 2. 3. 1. 1. 3. 1. 1. 2. 1. 1. 3.
 3. 2. 1. 2. 1. 1. 1. 1. 1. 1. 1. 1. 3. 1. 2. 1. 2. 2. 2. 1. 1. 1. 1. 1.
 1. 3. 1. 1. 1. 1. 1. 3. 3. 1. 2. 2. 1. 1. 1. 3. 1. 1. 1. 3. 1. 2. 1. 1.
 1. 1. 1. 3. 3. 1. 2. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 3. 1. 1. 2. 1. 1.
 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 3. 1. 1. 3. 1. 1. 1. 2. 3. 1.
 3. 2. 1. 2. 1. 1. 2. 1. 1. 1. 3. 1. 1. 1. 2. 2. 1.

[1. 3. 1. 1. 3. 1. 1. 1. 1. 1. 3. 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 2. 1. 1. 2. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 2. 1. 1. 2. 1. 1.
 2. 1. 1. 1. 1. 1. 2. 1. 1. 1. 3. 1. 1. 1. 1. 2. 1. 1. 2. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 2. 1. 3. 1. 1. 1. 1. 1. 1. 3. 2. 1. 1. 2. 1. 2.
 1. 1. 2. 1. 1. 1. 2. 1. 1. 1. 1. 1. 2. 3. 1. 1. 1. 1. 1. 1. 1. 1. 2. 1.
 1. 2. 1. 1. 1. 1. 1. 2. 1. 1. 3. 1. 2. 1. 1. 1. 1. 1. 1. 3. 1. 1. 2. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 3. 2. 3. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 3. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 1. 3. 1. 1. 3. 2. 1.
 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 2. 1. 2. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2.
 2. 1. 1. 1. 1. 1. 1. 3. 1. 1. 3. 1. 2. 2. 3. 1. 1. 1. 1. 2. 1. 1. 1. 2.
 2. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 3. 1. 1. 2. 3. 1. 1. 1. 1. 1. 2. 1. 1.
 1. 3. 1. 1. 1. 1. 3. 1. 2. 1. 1. 1. 1. 1. 3. 1. 1. 1. 1. 1. 1. 2. 1. 2.
 1. 1. 1. 1. 1. 1. 3. 1. 1. 1. 1. 2. 1. 1. 2. 1. 1. 1. 2. 3. 1. 2. 1. 1.
 1. 3. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1.

[1. 1. 1. 1. 1. 2. 1. 1. 2. 1. 1. 3. 1. 1. 1. 1. 1. 2. 1. 1. 2. 2. 3. 1.
 1. 1. 1. 1. 3. 1. 3. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 2. 1. 1.
 1. 1. 2. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 3. 1. 2. 1. 1. 1. 1.
 1. 1. 1. 1. 3. 2. 1. 1. 1. 1. 1. 1. 1. 3. 1. 1. 1. 1. 1. 3. 1. 1. 1. 1.
 1. 1. 1. 2. 1. 1. 2. 3. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 1. 3. 1. 1.
 1. 1. 1. 1. 1. 2. 2. 1. 1. 1. 1. 1. 1. 3. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 2. 2. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 1. 1.
 1. 1. 1. 1. 1. 3. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 3. 1. 1. 3. 1. 2. 1.
 1. 1. 3. 1. 2. 1. 1. 2. 1. 2. 1. 1. 1. 3. 1. 1. 2. 2. 1. 1. 1. 1. 1. 2.
 2. 2. 1. 2. 1. 3. 1. 1. 1. 1. 3. 3. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2.
 1. 1. 1. 1. 3. 1. 1. 1. 1. 3. 1. 1. 1. 3. 2. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 3. 1. 1. 1. 1. 1. 1. 1. 1. 3. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 2. 1. 1. 2. 3. 2. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 2. 3. 3.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 3. 1.

[1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 2. 1. 3. 2. 1. 1. 2. 1. 1. 2. 1. 1. 2. 1.
 3. 1. 1. 1. 3. 1. 1. 1. 2. 3. 1. 1. 1. 1. 1. 1. 1. 1. 2. 3. 1. 1. 1. 1.
 1. 1. 2. 2. 1. 1. 1. 2. 1. 1. 1. 3. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 2. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 2. 3. 1. 1. 1. 1. 3. 2. 1. 1.
 1. 2. 1. 1. 1. 1. 1. 2. 2. 1. 3. 2. 2. 1. 1. 1. 1. 3. 1. 1. 1. 1. 2. 1.
 2. 3. 1. 1. 1. 2. 1. 1. 1. 2. 1. 1. 2. 1. 3. 1. 1. 1. 1. 1. 2. 1. 1. 1.
 1. 1. 1. 1. 3. 1. 1. 1. 2. 1. 1. 1. 3. 1. 3. 1. 2. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 2. 1. 2. 1. 1. 1. 1. 3. 2. 1. 1. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 2. 1. 1. 1. 2. 3. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 3. 1. 3. 1. 1. 1.
 2. 1. 3. 1. 1. 1. 1. 1. 1. 1. 1. 1. 3. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 3. 1. 2. 1. 2. 3. 1. 3. 1. 1. 1. 1. 1. 1. 1. 1. 1. 3.
 1. 1. 1. 1. 1. 1. 1. 1. 2. 1. 2. 3. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 3. 1. 3. 2. 2. 1. 1. 1. 1. 1. 1. 1. 3. 1. 1. 1. 2.

[1. 1. 1. 3. 1. 1. 1. 1. 1. 2. 1. 1. 1. 3. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 3. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 3. 2. 1. 1. 2. 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 1. 2.
 1. 1. 1. 1. 3. 1. 3. 1. 1. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 3. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 2. 1. 2. 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 1.
 1. 2. 1. 3. 2. 1. 1. 1. 2. 2. 2. 1. 2. 1. 1. 3. 2. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 3. 2. 1. 1. 1. 2. 2. 2. 2. 1. 1. 1. 1. 1. 1. 3. 1. 1. 3. 2. 1. 2.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 3. 2. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 1. 1.
 1. 1. 1. 3. 1. 2. 1. 3. 1. 1. 2. 1. 2. 1. 3. 1. 1. 2. 3. 1. 1. 3. 2. 1.
 3. 1. 1. 1. 3. 2. 1. 2. 1. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 3. 3. 3. 3. 2.
 2. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 3. 2. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 3. 2. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 2. 1. 1. 1. 1. 1. 2. 1. 1. 3.
 2. 1. 1. 2. 1. 1. 1. 1. 1. 3. 1. 1. 3. 3. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 3. 1. 1. 1. 1. 1. 1. 1. 1. 3. 2. 1. 1. 2. 1.

[3. 1. 1. 1. 1. 3. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1.
 1. 1. 1. 2. 2. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 2. 1. 1. 1. 3. 2.
 2. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 3. 1. 1. 1. 1. 1. 1. 1. 1. 2. 1.
 1. 2. 1. 1. 1. 3. 1. 1. 1. 1. 3. 1. 2. 2. 1. 1. 1. 1. 2. 2. 1. 1. 1. 3.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 3. 1. 3. 1. 3. 2. 1. 1. 1. 3. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 3. 1. 3. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 3. 1. 1. 1. 2. 1. 1. 3. 1. 1. 1. 1. 2. 2.
 1. 1. 2. 1. 1. 2. 3. 2. 1. 1. 1. 1. 1. 3. 2. 2. 1. 1. 2. 1. 1. 3. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 3. 2. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 2. 1. 1. 2. 2. 1. 2. 1. 1. 1. 3. 1. 1. 1. 2. 1. 2. 1.
 3. 2. 2. 3. 1. 2. 1. 1. 1. 1. 3. 1. 1. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 2.
 1. 1. 3. 1. 1. 1. 1. 1. 3. 1. 1. 1. 2. 2. 1. 1. 1. 1. 2. 1. 2. 1. 2. 1.
 2. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 3. 1. 2. 1. 1. 2. 1. 1. 1.
 1. 3. 3. 2. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 3. 1. 1.

[1. 1. 1. 1. 1. 1. 1. 3. 2. 3. 1. 1. 1. 3. 1. 1. 1. 1. 1. 3. 2. 1. 1. 2.
 1. 1. 1. 1. 2. 1. 1. 3. 1. 1. 1. 2. 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 3. 2. 1. 3. 1. 2. 1. 1. 1. 1. 1. 2. 1. 1. 2.
 1. 2. 1. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 1. 2. 1. 1. 2. 1. 1.
 1. 3. 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 3. 1.
 1. 1. 2. 2. 1. 1. 1. 1. 1. 3. 1. 1. 2. 1. 1. 1. 1. 2. 1. 1. 3. 1. 1. 2.
 2. 1. 1. 2. 1. 2. 1. 1. 1. 2. 3. 1. 3. 1. 2. 1. 1. 1. 2. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 2. 1. 1. 1. 3. 1. 1. 1. 1. 3. 1. 3. 3. 1.
 1. 1. 1. 1. 1. 3. 1. 3. 1. 1. 1. 1. 2. 1. 3. 2. 2. 1. 1. 1. 1. 2. 2. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 1. 1. 2. 1. 1. 1. 1. 1. 2. 1. 1.
 1. 1. 3. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 3. 1. 1.
 2. 1. 2. 1. 2. 1. 2. 1. 2. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 2. 3. 2. 2. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 1. 1. 3. 1. 2. 1. 1. 1. 1.
 2. 1. 3. 1. 3. 1. 1. 1. 2. 1. 1. 1. 1. 1. 3. 1. 1.

[1. 1. 3. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 3. 1. 1. 3. 1.
 1. 1. 1. 2. 1. 2. 1. 2. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 3. 1. 1. 3.
 1. 1. 1. 3. 1. 1. 1. 2. 2. 1. 2. 1. 1. 1. 1. 1. 1. 1. 1. 2. 1. 3. 1. 2.
 1. 1. 2. 1. 1. 1. 2. 3. 2. 1. 2. 1. 1. 3. 1. 3. 1. 2. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 1. 2. 1. 1. 1. 1. 1. 1. 1. 1. 3. 1.
 2. 1. 1. 1. 1. 1. 1. 1. 1. 2. 1. 1. 2. 3. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 2. 1. 1. 1. 1.
 3. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 1. 2. 1. 3. 2. 1. 1. 1. 3. 1. 1. 1. 3.
 2. 3. 2. 1. 1. 1. 3. 1. 1. 3. 1. 3. 2. 1. 3. 1. 1. 3. 1. 1. 1. 1. 1. 2.
 1. 2. 1. 1. 1. 1. 1. 1. 3. 2. 1. 1. 2. 1. 1. 1. 1. 1. 1. 3. 2. 1. 1. 1.
 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 3. 1. 1. 1. 1. 2. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 3. 1. 1. 1. 2. 1. 2. 1. 1. 1. 1. 1. 1. 1. 1. 2.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 1.
 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 2. 1. 2. 1. 1. 1. 2.

[1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 3. 1. 2. 2. 3. 1. 1. 1. 1. 1. 1. 3. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 2. 1. 1. 1. 2. 1. 1. 1. 3. 1. 1. 1. 1.
 3. 1. 2. 3. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 2. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 3. 1. 3. 2. 1. 1. 1. 1. 1. 1. 1. 3. 1. 1. 1. 1. 1.
 1. 2. 3. 1. 1. 3. 1. 2. 1. 1. 2. 1. 1. 2. 1. 1. 1. 1. 1. 2. 2. 2. 1. 2.
 1. 2. 1. 3. 1. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 3. 1. 1. 1. 1. 1. 2. 1. 2.
 1. 1. 1. 1. 2. 3. 1. 2. 1. 1. 3. 3. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 3. 1.
 3. 3. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 2. 1. 1. 2. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 3. 1. 2. 2. 3. 1. 1. 1.
 1. 1. 1. 2. 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 1. 2. 1. 2. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 2. 3. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 3. 3. 1. 3. 1. 2. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 2. 1. 3. 1. 1. 2. 1. 1. 1. 1. 1. 1. 2. 1. 1. 2. 2.
 1. 1. 1. 1. 1. 1. 2. 1. 2. 1. 3. 1. 1. 1. 1. 1. 1.

[1. 2. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 2. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 3. 2. 1. 1.
 1. 1. 3. 1. 2. 3. 1. 1. 2. 1. 1. 2. 1. 1. 1. 1. 3. 1. 1. 2. 1. 1. 1. 2.
 2. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 2.
 3. 1. 2. 1. 1. 2. 1. 1. 1. 1. 1. 1. 2. 1. 2. 1. 1. 1. 1. 1. 1. 1. 2. 1.
 2. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 3. 1. 1. 3. 1. 1. 3. 1. 3. 1. 1. 3. 1. 1. 1. 1. 1. 1. 2. 1.
 1. 1. 1. 1. 2. 3. 1. 1. 1. 1. 1. 1. 3. 1. 1. 1. 3. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 3. 1. 1. 1. 2. 2. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 2. 1.
 2. 1. 1. 1. 1. 1. 1. 2. 1. 3. 1. 1. 1. 2. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1.
 1. 1. 1. 3. 2. 1. 1. 1. 1. 1. 1. 1. 3. 3. 1. 1. 1. 1. 1. 1. 3. 3. 3. 1.
 1. 1. 1. 1. 2. 1. 2. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 2. 1.
 2. 1. 1. 1. 1. 1. 1. 1. 1. 2. 1. 1. 2. 1. 2. 1. 1. 1. 3. 1. 2. 1. 1. 1.
 2. 1. 2. 1. 2. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.

In [3]:
print("==================================================")
print("Confiabidad 80(train)/20(test)    :             | ")
print("==================================================")
print(np.median(confiabilidad),"%")
print("==================================================")

Confiabidad 80(train)/20(test)    :             | 
0.8791079812206573 %


2. Segunda Ejecucion

In [4]:

shufflesplit=StratifiedShuffleSplit(n_splits=100, test_size=0.50, random_state=0)
cv=shufflesplit.split(X,Y)

for indice, (train_index, test_index) in enumerate( cv):
    print("-----")
    print("Split: ",indice)
    clasificador.fit(X[train_index],Y[train_index])
    y_obtenido = clasificador.predict(X[test_index])
    print(Y[test_index])
    print(y_obtenido)
    print("")
    print("Matriz de Confusión")
    print(confusion_matrix(y_obtenido,Y[test_index]))
    print("Precisión")
    c1=precision_score(y_obtenido, Y[test_index], average='micro')
    print(c1)
    confiabilidad[indice]=c1


-----
Split:  0
[1. 1. 1. ... 1. 1. 1.]
[1. 1. 1. ... 1. 1. 1.]

Matriz de Confusión
[[781  58   9]
 [ 37  86   7]
 [ 10   3  72]]
Precisión
0.883349012229539
-----
Split:  1
[1. 1. 1. ... 1. 1. 1.]
[1. 1. 1. ... 1. 1. 1.]

Matriz de Confusión
[[779  54   8]
 [ 39  86  10]
 [ 10   7  70]]
Precisión
0.8795860771401693
-----
Split:  2
[1. 1. 1. ... 1. 1. 1.]
[1. 1. 1. ... 1. 1. 1.]

Matriz de Confusión
[[781  57   7]
 [ 38  88  12]
 [  8   3  69]]
Precisión
0.8824082784571966
-----
Split:  3
[1. 1. 1. ... 1. 1. 1.]
[1. 1. 1. ... 1. 1. 2.]

Matriz de Confusión
[[778  57   9]
 [ 37  80  13]
 [ 12  11  66]]
Precisión
0.8692380056444027
-----
Split:  4
[2. 1. 1. ... 1. 1. 1.]
[1. 1. 1. ... 1. 1. 1.]

Matriz de Confusión
[[793  73   8]
 [ 23  71  12]
 [ 12   3  68]]
Precisión
0.8767638758231421
-----
Split:  5
[2. 1. 2. ... 1. 1. 1.]
[1. 1. 3. ... 1. 1. 1.]

Matriz de Confusión
[[769  65  10]
 [ 45  78  15]
 [ 14   4  63]]
Precisión
0.8560677328316086
-----
Split:  6
[1. 1. 1. ... 1. 1. 1.]
[

[1. 1. 1. ... 1. 1. 1.]
[1. 1. 1. ... 1. 1. 1.]

Matriz de Confusión
[[799  73   7]
 [ 24  74  12]
 [  4   1  69]]
Precisión
0.8861712135465664
-----
Split:  52
[3. 1. 1. ... 1. 1. 1.]
[3. 1. 1. ... 1. 1. 1.]

Matriz de Confusión
[[775  61   7]
 [ 38  79  10]
 [ 15   7  71]]
Precisión
0.8701787394167451
-----
Split:  53
[1. 1. 1. ... 2. 1. 1.]
[1. 1. 1. ... 2. 1. 1.]

Matriz de Confusión
[[780  62   9]
 [ 37  83  12]
 [ 10   3  67]]
Precisión
0.8748824082784572
-----
Split:  54
[3. 1. 1. ... 1. 1. 1.]
[3. 1. 1. ... 1. 1. 1.]

Matriz de Confusión
[[765  69   5]
 [ 42  65  12]
 [ 21  13  71]]
Precisión
0.8476011288805269
-----
Split:  55
[2. 1. 2. ... 3. 2. 2.]
[2. 1. 2. ... 1. 2. 2.]

Matriz de Confusión
[[790  56   7]
 [ 30  88  11]
 [  8   3  70]]
Precisión
0.8918156161806209
-----
Split:  56
[1. 1. 1. ... 1. 1. 1.]
[1. 1. 1. ... 1. 1. 1.]

Matriz de Confusión
[[786  64  11]
 [ 34  78   9]
 [  7   6  68]]
Precisión
0.8767638758231421
-----
Split:  57
[1. 1. 1. ... 1. 1. 1.]
[1. 1. 1. 

In [7]:
    
print("==================================================")
print("Confiabidad 50(train)/50(test)    :             | ")
print("==================================================")
print(np.median(confiabilidad),"%")
print("==================================================")


Confiabidad 50(train)/50(test)    :             | 
0.8730009407337723 %
