# Segundo código

In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

#Leyendo el archivo CSV
data= pd.read_csv("fetal_health.csv", sep=",", header=[0])
print(data.describe())
X = data.iloc[:, :-1].values
y= data.iloc[:,21].values

from sklearn.impute import SimpleImputer
from sklearn import preprocessing
from sklearn.tree import DecisionTreeClassifier
from sklearn.decomposition import PCA
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix
from sklearn.metrics import precision_score
imputer = SimpleImputer(missing_values=np.NaN, strategy='mean')
imputer = imputer.fit(X)
X= imputer.transform(X)

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

presicion=np.zeros((19,2))
numeros=[3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21]
for i in numeros:
    print("==================================================")
    print(i)
    pca = PCA(n_components = i)
    X_trainb = pca.fit_transform(X_train)
    X_testb = pca.transform(X_test)
    #explained_variance = pca.explained_variance_ratio_
    classifier = LogisticRegression()
    #classifier = LogisticRegression()
    classifier = DecisionTreeClassifier()
    classifier.fit(X_trainb, y_train)
    y_predb = classifier.predict(X_testb)
    cm = confusion_matrix(y_test, y_predb)
    presicion[i-3][0]=i
    print("Matriz de confusión :                             | ")
    print(cm)
    print("Precisión           :                            | ")
    presicion[i-3][1]=precision_score(y_test, y_predb,average='micro')
    print(presicion[i-3][1])
    print("==================================================")
    
ordenados = sorted(presicion, key=lambda num : num[1],reverse = True)
print('Confiabilidad por numero de columnas:')
print('Nro de columnas', "   Presicion")
for i in ordenados:
    print(int(i[0]),"             ",i[1])


       baseline value  accelerations  fetal_movement  uterine_contractions  \
count     2126.000000    2126.000000     2126.000000           2126.000000   
mean       133.303857       0.003178        0.009481              0.004366   
std          9.840844       0.003866        0.046666              0.002946   
min        106.000000       0.000000        0.000000              0.000000   
25%        126.000000       0.000000        0.000000              0.002000   
50%        133.000000       0.002000        0.000000              0.004000   
75%        140.000000       0.006000        0.003000              0.007000   
max        160.000000       0.019000        0.481000              0.015000   

       light_decelerations  severe_decelerations  prolongued_decelerations  \
count          2126.000000           2126.000000               2126.000000   
mean              0.001889              0.000003                  0.000159   
std               0.002960              0.000057               

Matriz de confusión :                             | 
[[303  18   5]
 [ 21  30   7]
 [  2   5  35]]
Precisión           :                            | 
0.863849765258216
17
Matriz de confusión :                             | 
[[300  19   7]
 [ 22  32   4]
 [  4   3  35]]
Precisión           :                            | 
0.8615023474178404
18
Matriz de confusión :                             | 
[[301  20   5]
 [ 23  29   6]
 [  2   6  34]]
Precisión           :                            | 
0.8544600938967136
19
Matriz de confusión :                             | 
[[299  21   6]
 [ 23  28   7]
 [  2   7  33]]
Precisión           :                            | 
0.8450704225352113
20
Matriz de confusión :                             | 
[[297  23   6]
 [ 24  29   5]
 [  4   3  35]]
Precisión           :                            | 
0.8474178403755869
21
Matriz de confusión :                             | 
[[298  22   6]
 [ 24  30   4]
 [  2   6  34]]
Precisión           :                

In [3]:
###############################################################################
pca=PCA(n_components= int(ordenados[0][0]))
X=pca.fit_transform(X)
clasificador =LogisticRegression()
from sklearn.model_selection import StratifiedShuffleSplit
shufflesplit=StratifiedShuffleSplit(n_splits=100, test_size=0.20, random_state=0)
cv=shufflesplit.split(X,y)
confiabilidad1=np.zeros(100)
confiabilidad2=np.zeros(100)
for indice, (train_index, test_index) in enumerate( cv):
    clasificador.fit(X[train_index],y[train_index])
    y_obtenido = clasificador.predict(X[test_index])
    #print(y[test_index])
    #print(y_obtenido)
    #print("")
    #print("Matriz de Confusión")
    #print(confusion_matrix(y_obtenido,y[test_index]))
    
    c1=precision_score(y_obtenido, y[test_index], average='micro')
    print("-----Split: ",indice, " -- Precisión",c1)
    confiabilidad1[indice]=c1

shufflesplit=StratifiedShuffleSplit(n_splits=100, test_size=0.50, random_state=0)
cv=shufflesplit.split(X,y)
confiabilidad=np.zeros(100)
for indice, (train_index, test_index) in enumerate( cv):
        
    clasificador.fit(X[train_index],y[train_index])
    y_obtenido = clasificador.predict(X[test_index])
    #print(y[test_index])
    #print(y_obtenido)
    #print("")
    #print("Matriz de Confusión")
    #print(confusion_matrix(y_obtenido,y[test_index]))
    
    c1=precision_score(y_obtenido, y[test_index], average='micro')
    print("-----Split: ",indice, " -- Precisión",c1)
    confiabilidad2[indice]=c1
    
print("==================================================")
print("Confiabidad 80(train)/20(test)    :             | ")
print("==================================================")
print(np.median(confiabilidad1))
print("==================================================")
    
print("==================================================")
print("Confiabidad 50(train)/50(test)    :             | ")
print("==================================================")
print(np.median(confiabilidad2))
print("==================================================")


-----Split:  0  -- Precisión 0.8779342723004695
-----Split:  1  -- Precisión 0.8661971830985915
-----Split:  2  -- Precisión 0.8826291079812206
-----Split:  3  -- Precisión 0.8497652582159625
-----Split:  4  -- Precisión 0.8661971830985915
-----Split:  5  -- Precisión 0.8591549295774648
-----Split:  6  -- Precisión 0.8779342723004695
-----Split:  7  -- Precisión 0.8661971830985915
-----Split:  8  -- Precisión 0.8591549295774648
-----Split:  9  -- Precisión 0.8568075117370892
-----Split:  10  -- Precisión 0.8732394366197183
-----Split:  11  -- Precisión 0.863849765258216
-----Split:  12  -- Precisión 0.8685446009389671
-----Split:  13  -- Precisión 0.8615023474178404
-----Split:  14  -- Precisión 0.8474178403755869
-----Split:  15  -- Precisión 0.8497652582159625
-----Split:  16  -- Precisión 0.8708920187793427
-----Split:  17  -- Precisión 0.8685446009389671
-----Split:  18  -- Precisión 0.8474178403755869
-----Split:  19  -- Precisión 0.863849765258216
-----Split:  20  -- Precisión 0.

-----Split:  69  -- Precisión 0.8777046095954845
-----Split:  70  -- Precisión 0.8701787394167451
-----Split:  71  -- Precisión 0.8579492003762935
-----Split:  72  -- Precisión 0.8598306679209784
-----Split:  73  -- Precisión 0.8579492003762935
-----Split:  74  -- Precisión 0.8692380056444027
-----Split:  75  -- Precisión 0.8551269990592663
-----Split:  76  -- Precisión 0.8532455315145814
-----Split:  77  -- Precisión 0.8626528692380057
-----Split:  78  -- Precisión 0.8692380056444027
-----Split:  79  -- Precisión 0.8570084666039511
-----Split:  80  -- Precisión 0.8664158043273753
-----Split:  81  -- Precisión 0.8588899341486359
-----Split:  82  -- Precisión 0.8560677328316086
-----Split:  83  -- Precisión 0.8682972718720602
-----Split:  84  -- Precisión 0.8626528692380057
-----Split:  85  -- Precisión 0.8494825964252116
-----Split:  86  -- Precisión 0.8551269990592663
-----Split:  87  -- Precisión 0.8570084666039511
-----Split:  88  -- Precisión 0.8692380056444027
-----Split:  89  -- 